---
- auth:create-role:repo:github.com/mozilla-platform-ops/cloud-image-builder:branch:*
- auth:update-role:repo:github.com/mozilla-platform-ops/cloud-image-builder:branch:*
- generic-worker:os-group:relops-3/win2019/Administrators
- generic-worker:run-as-administrator:relops-3/*
- queue:create-task:high:relops-3/*
- queue:create-task:highest:relops-3/*
- queue:create-task:low:relops-3/*
- queue:create-task:medium:relops-3/*
- queue:create-task:very-high:relops-3/*
- queue:create-task:high:gecko-t/win*
- queue:create-task:high:gecko-1/win*
- queue:create-task:high:gecko-3/win*
- queue:create-task:high:mpd001-1/win*
- queue:create-task:high:mpd001-3/win*
- queue:create-task:very-high:gecko-t/win*
- queue:create-task:very-high:gecko-1/win*
- queue:create-task:very-high:gecko-3/win*
- queue:create-task:very-high:mpd001-1/win*
- queue:create-task:very-high:mpd001-3/win*
- queue:route:index.project.relops-3.cloud-image-builder.*
- queue:scheduler-id:-
- queue:scheduler-id:taskcluster-github
- secrets:get:project/relops/image-builder/dev
- worker-manager:manage-worker-pool:gecko-1/win*
- worker-manager:manage-worker-pool:gecko-3/win*
- worker-manager:manage-worker-pool:gecko-t/win*
- worker-manager:manage-worker-pool:mpd001-1/win*
- worker-manager:manage-worker-pool:mpd001-3/win*
- worker-manager:manage-worker-pool:relops-3/*
- worker-manager:provider:aws
- worker-manager:provider:azure
