---
version: 0
tasks:
    - provisionerId: relops-3
      workerType: decision
      routes:
          - index.project.relops.cloud-image-builder.decision.revision.{{event.head.sha}}
          - index.project.relops.cloud-image-builder.decision.latest
      scopes:
          - assume:repo:github.com/mozilla-platform-ops/cloud-image-builder:branch:{{event.head.repo.branch}}
          - queue:scheduler-id:taskcluster-github
      extra:
          github:
              env: true
              events:
                  # - pull_request.*
                  - push
          data:
              base:
                  sha: '{{event.base.sha}}'
                  user:
                      login: '{{event.base.user.login}}'
              head:
                  sha: '{{event.head.sha}}'
                  user:
                      email: '{{event.head.user.email}}'
      payload:
          maxRunTime: 600
          image: python
          features:
              taskclusterProxy: true
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - >-
                  pip install azure-mgmt-compute | grep -v "^[[:space:]]*$"
                  && pip install boto3 | grep -v "^[[:space:]]*$"
                  && pip install cachetools | grep -v "^[[:space:]]*$"
                  && pip install pyyaml | grep -v "^[[:space:]]*$"
                  && pip install slugid | grep -v "^[[:space:]]*$"
                  && pip install taskcluster | grep -v "^[[:space:]]*$"
                  && pip install urllib3 | grep -v "^[[:space:]]*$"
                  && git clone --quiet {{event.head.repo.url}}
                  && cd cloud-image-builder
                  && git fetch
                  && git checkout {{event.head.repo.branch}}
                  && git reset --hard {{event.head.sha}}
                  && python ci/create-image-build-tasks.py
      metadata:
          name: '00 :: create maintenance and image build tasks'
          description: >-
              determine which cloud images should be built, where they should
              \ be deployed and trigger appropriate build tasks for the same
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'
