---
win10-64-azure:
  image:
    os: Windows 10
    edition: Professional
    language: en-US
    architecture: x86-64
    gpu: false
    owner: Mozilla RelOps
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
  iso:
    source:
      platform: amazon
      bucket: windows-ami-builder
      key: iso/en_windows_10_business_editions_version_1903_updated_sept_2019_x64_dvd_a10b235d.iso
    wimindex: 5
  target:
  - platform: azure
    group: rg-central-us-gecko-t
    region: Central US
    hostname:
      format: vm-{0}
      slug:
        type: uuid
        length: 12
    machine:
      cpu: 2
      ram: 8
    disk:
    - os: true
      source: windows10-professional-en-us-x86-64
      variant: ssd
      size: 64
    network:
      name: vn-central-us-gecko-t
      prefix: '10.0.0.0/16'
      dns:
      - '1.1.1.1'
      - '1.0.0.1'
      subnet:
        name: sn-central-us-gecko-t
        prefix: '10.0.4.0/24'
      flow:
        name: nsg-central-us-gecko-t
        rules:
        - name: allow-rdp
          description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
          access: Allow
          Protocol: Tcp
          Direction: Inbound
          Priority: 110
          SourceAddressPrefix:
          - 185.189.196.216
          SourcePortRange: '*'
          DestinationAddressPrefix: '*'
          DestinationPortRange: 3389
        - name: allow-ssh
          description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
          access: Allow
          Protocol: Tcp
          Direction: Inbound
          Priority: 111
          SourceAddressPrefix:
          - 185.189.196.216
          SourcePortRange: '*'
          DestinationAddressPrefix: '*'
          DestinationPortRange: 22
    tag:
    - name: workerType
      value: gecko-t-win10-64-azure
    - name: sourceOrganisation
      value: mozilla-releng
    - name: sourceRepository
      value: OpenCloudConfig
    - name: sourceRevision
      value: azure
win10-64-gpu-azure:
  image:
    os: Windows 10
    edition: Professional
    language: en-US
    architecture: x86-64
    gpu: true
    owner: Mozilla RelOps
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
  iso:
    source:
      platform: amazon
      bucket: windows-ami-builder
      key: iso/en_windows_10_business_editions_version_1903_updated_sept_2019_x64_dvd_a10b235d.iso
    wimindex: 5
  target:
  - platform: azure
    group: rg-central-us-gecko-t
    region: Central US
    hostname:
      format: vm-{0}
      slug:
        type: uuid
        length: 12
    machine:
      cpu: 2
      ram: 8
    disk:
    - os: true
      source: windows10-professional-en-us-x86-64-gpu
      variant: ssd
      size: 64
    network:
      name: vn-central-us-gecko-t
      prefix: '10.0.0.0/16'
      dns:
      - '1.1.1.1'
      - '1.0.0.1'
      subnet:
        name: sn-central-us-gecko-t
        prefix: '10.0.4.0/24'
      flow:
        name: nsg-central-us-gecko-t
        rules:
        - name: allow-rdp
          description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
          access: Allow
          Protocol: Tcp
          Direction: Inbound
          Priority: 110
          SourceAddressPrefix:
          - 185.189.196.216
          SourcePortRange: '*'
          DestinationAddressPrefix: '*'
          DestinationPortRange: 3389
        - name: allow-ssh
          description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
          access: Allow
          Protocol: Tcp
          Direction: Inbound
          Priority: 111
          SourceAddressPrefix:
          - 185.189.196.216
          SourcePortRange: '*'
          DestinationAddressPrefix: '*'
          DestinationPortRange: 22
    tag:
    - name: workerType
      value: gecko-t-win10-64-gpu-azure
    - name: sourceOrganisation
      value: mozilla-releng
    - name: sourceRepository
      value: OpenCloudConfig
    - name: sourceRevision
      value: azure
win2012-azure:
  image:
    os: Windows Server 2012 R2
    edition: Datacenter
    language: en-US
    architecture: x86-64
    gpu: false
    owner: Mozilla RelOps
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
  iso:
    source:
      platform: amazon
      bucket: windows-ami-builder
      key: iso/en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso
    wimindex: 4
  target:
  - platform: azure
    group: rg-central-us-gecko-1
    region: Central US
    hostname:
      format: vm-{0}
      slug:
        type: uuid
        length: 12
    machine:
      cpu: 2
      ram: 8
    disk:
    - os: true
      source: windowsserver2012r2-datacenter-en-us-x86-64
      variant: ssd
      size: 64
    network:
      name: vn-central-us-gecko-1
      prefix: '10.0.0.0/16'
      dns:
      - '1.1.1.1'
      - '1.0.0.1'
      subnet:
        name: sn-central-us-gecko-1
        prefix: '10.0.1.0/24'
      flow:
        name: nsg-central-us-gecko-1
        rules:
        - name: allow-rdp
          description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
          access: Allow
          Protocol: Tcp
          Direction: Inbound
          Priority: 110
          SourceAddressPrefix:
          - 185.189.196.216
          SourcePortRange: '*'
          DestinationAddressPrefix: '*'
          DestinationPortRange: 3389
        - name: allow-ssh
          description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
          access: Allow
          Protocol: Tcp
          Direction: Inbound
          Priority: 111
          SourceAddressPrefix:
          - 185.189.196.216
          SourcePortRange: '*'
          DestinationAddressPrefix: '*'
          DestinationPortRange: 22
    tag:
    - name: workerType
      value: gecko-1-b-win2012-azure
    - name: sourceOrganisation
      value: mozilla-releng
    - name: sourceRepository
      value: OpenCloudConfig
    - name: sourceRevision
      value: azure
win2019-azure:
  image:
    os: Windows Server 2019
    edition: Datacenter
    language: en-US
    architecture: x86-64
    gpu: false
    owner: Mozilla RelOps
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
  iso:
    source:
      platform: amazon
      bucket: windows-ami-builder
      key: iso/en_windows_server_2019_updated_sept_2019_x64_dvd_199664ce.iso
    wimindex: 4
  target:
  - platform: azure
    group: rg-central-us-relops
    region: Central US
    hostname:
      format: vm-{0}
      slug:
        type: uuid
        length: 12
    machine:
      cpu: 2
      ram: 8
    disk:
    - os: true
      source: windowsserver2019-datacenter-en-us-x86-64
      variant: ssd
      size: 64
    network:
      name: vn-central-us-relops
      prefix: '10.0.0.0/16'
      dns:
      - '1.1.1.1'
      - '1.0.0.1'
      subnet:
        name: sn-central-us-relops
        prefix: '10.0.6.0/24'
      flow:
        name: nsg-central-us-relops
        rules:
        - name: allow-rdp
          description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
          access: Allow
          Protocol: Tcp
          Direction: Inbound
          Priority: 110
          SourceAddressPrefix:
          - 185.189.196.216
          SourcePortRange: '*'
          DestinationAddressPrefix: '*'
          DestinationPortRange: 3389
        - name: allow-ssh
          description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
          access: Allow
          Protocol: Tcp
          Direction: Inbound
          Priority: 111
          SourceAddressPrefix:
          - 185.189.196.216
          SourcePortRange: '*'
          DestinationAddressPrefix: '*'
          DestinationPortRange: 22
    tag:
    - name: workerType
      value: relops-win2019-azure
    - name: sourceOrganisation
      value: mozilla-releng
    - name: sourceRepository
      value: OpenCloudConfig
    - name: sourceRevision
      value: azure