---
win10-64-azure:
  image:
    os: Windows 10
    edition: Professional
    language: en-US
    architecture: x86-64
    gpu: false
    owner: Mozilla RelOps
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
  iso:
    source:
      platform: amazon
      bucket: windows-ami-builder
      key: iso/en_windows_10_business_editions_version_1903_updated_sept_2019_x64_dvd_a10b235d.iso
    wimindex: 5
  target:
  - platform: azure
    group: gecko-t
    region: East US
    hostname:
      format: vm-{0}
      slug:
        type: uuid
        length: 12
    machine:
      type: Standard_A2
    disk:
    - os: true
      source: windows10-professional-en-us-x86-64
      type: StandardSSD_LRS
      size: 64
    network:
      name: gecko-t-vnet
      flow:
      - nsg-gecko-t
    tag:
    - name: workerType
      value: gecko-t-win10-64-azure
    - name: sourceOrganisation
      value: mozilla-releng
    - name: sourceRepository
      value: OpenCloudConfig
    - name: sourceRevision
      value: azure
win10-64-gpu-azure:
  image:
    os: Windows 10
    edition: Professional
    language: en-US
    architecture: x86-64
    gpu: true
    owner: Mozilla RelOps
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
  iso:
    source:
      platform: amazon
      bucket: windows-ami-builder
      key: iso/en_windows_10_business_editions_version_1903_updated_sept_2019_x64_dvd_a10b235d.iso
    wimindex: 5
  target:
  - platform: azure
    group: gecko-t
    region: East US
    hostname:
      format: vm-{0}
      slug:
        type: uuid
        length: 12
    machine:
      type: Standard_A2
    disk:
    - os: true
      source: windows10-professional-en-us-x86-64-gpu
      type: StandardSSD_LRS
      size: 64
    network:
      name: gecko-t-vnet
      flow:
      - nsg-gecko-t
    tag:
    - name: workerType
      value: gecko-t-win10-64-gpu-azure
    - name: sourceOrganisation
      value: mozilla-releng
    - name: sourceRepository
      value: OpenCloudConfig
    - name: sourceRevision
      value: azure
win2012-azure:
  image:
    os: Windows Server 2012 R2
    edition: Datacenter
    language: en-US
    architecture: x86-64
    gpu: false
    owner: Mozilla RelOps
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
  iso:
    source:
      platform: amazon
      bucket: windows-ami-builder
      key: iso/en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso
    wimindex: 4
  target:
  - platform: azure
    group: gecko-1
    region: East US
    hostname:
      format: vm-{0}
      slug:
        type: uuid
        length: 12
    machine:
      type: Standard_A2
    disk:
    - os: true
      source: windowsserver2012r2-datacenter-en-us-x86-64
      type: StandardSSD_LRS
      size: 64
    network:
      name: gecko-1-vnet
      flow:
      - nsg-gecko-1
    tag:
    - name: workerType
      value: gecko-1-b-win2012-azure
    - name: sourceOrganisation
      value: mozilla-releng
    - name: sourceRepository
      value: OpenCloudConfig
    - name: sourceRevision
      value: azure
win2019-azure:
  image:
    os: Windows Server 2019
    edition: Datacenter
    language: en-US
    architecture: x86-64
    gpu: false
    owner: Mozilla RelOps
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
  iso:
    source:
      platform: amazon
      bucket: windows-ami-builder
      key: iso/en_windows_server_2019_updated_sept_2019_x64_dvd_199664ce.iso
    wimindex: 4
  target:
  - platform: azure
    group: relops
    region: East US
    hostname:
      format: vm-{0}
      slug:
        type: uuid
        length: 12
    machine:
      type: Standard_A2
    disk:
    - os: true
      source: windowsserver2019-datacenter-en-us-x86-64
      type: StandardSSD_LRS
      size: 64
    network:
      name: relops-vnet
      flow:
      - nsg-relops
    tag:
    - name: workerType
      value: gecko-1-b-win2019-azure
    - name: sourceOrganisation
      value: mozilla-releng
    - name: sourceRepository
      value: OpenCloudConfig
    - name: sourceRevision
      value: azure