---
- 'generic-worker:os-group:relops/win2019/Administrators'
- 'generic-worker:run-as-administrator:relops/win2019'
- 'queue:create-task:highest:relops/win2019'
- 'queue:route:index.project.relops.cloud-image-builder.*'
- 'queue:scheduler-id:-'
- 'secrets:get:project/relops/image-builder/dev'
- 'worker-manager:manage-worker-pool:relops/win*'
- 'worker-manager:provider:aws'