---
description: build windows cloud images for taskcluster windows workloads
scopes:
    - generic-worker:os-group:relops/win2019/Administrators
    - generic-worker:run-as-administrator:relops/*
    - queue:create-task:highest:relops/*
    - queue:create-task:very-high:relops/*
    - queue:create-task:high:relops/*
    - queue:create-task:medium:relops/*
    - queue:create-task:low:relops/*
    - queue:create-task:high:gecko-t/win*
    - queue:create-task:high:gecko-1/win*
    - queue:create-task:high:gecko-3/win*
    - queue:create-task:high:mpd001-1/win*
    - queue:create-task:high:mpd001-3/win*
    - queue:create-task:very-high:gecko-t/win*
    - queue:create-task:very-high:gecko-1/win*
    - queue:create-task:very-high:gecko-3/win*
    - queue:create-task:very-high:mpd001-1/win*
    - queue:create-task:very-high:mpd001-3/win*
    - queue:route:index.project.relops.cloud-image-builder.*
    - worker-manager:manage-worker-pool:gecko-1/win*
    - worker-manager:manage-worker-pool:gecko-3/win*
    - worker-manager:manage-worker-pool:gecko-t/win*
    - worker-manager:manage-worker-pool:mpd001-1/win*
    - worker-manager:manage-worker-pool:mpd001-3/win*
    - worker-manager:manage-worker-pool:relops/win*
    - worker-manager:provider:aws
    - worker-manager:provider:azure
    - secrets:get:project/relops/image-builder/dev
