---
- name: SecurityHealthService
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 10
      architecture:
          - x86
          - x86-64
- name: Sense
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 10
      architecture:
          - x86
          - x86-64
- name: WdBoot
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 10
      architecture:
          - x86
          - x86-64
- name: WdFilter
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 10
      architecture:
          - x86
          - x86-64
- name: WdNisDrv
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 10
      architecture:
          - x86
          - x86-64
- name: WdNisSvc
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 10
      architecture:
          - x86
          - x86-64
- name: WinDefend
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 10
      architecture:
          - x86
          - x86-64
- name: wscsvc
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 10
      architecture:
          - x86
          - x86-64
