---
- name: StackdriverLogging-v1-9.exe
  savepath: Windows\Temp\StackdriverLogging-v1-9.exe
  unattend:
      - description: create log folder
        command: cmd /c if not exist C:\log mkdir C:\log
      - description: install stackdriver
        command: C:\Windows\Temp\StackdriverLogging-v1-9.exe /S
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: amazon
        bucket: windows-ami-builder
        key: package/StackdriverLogging-v1-9.exe
- name: nxlog-ce.msi
  savepath: Windows\Temp\nxlog-ce.msi
  unattend:
      - description: create log folder
        command: cmd /c if not exist C:\log mkdir C:\log
      - description: install nxlog
        # yamllint disable-line rule:line-length
        command: msiexec /i C:\Windows\Temp\nxlog-ce.msi /q /L*v C:\log\unattend-install-nxlog-stdout.log
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: amazon
        bucket: windows-ami-builder
        key: package/nxlog-ce-2.10.2150.msi
      - platform: google
        bucket: windows-ami-builder
        key: package/nxlog-ce-2.10.2150.msi
      - platform: azure
        bucket: windows-ami-builder
        key: package/nxlog-ce-2.10.2150.msi
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://nxlog.co/system/files/products/files/348/nxlog-ce-2.10.2150.msi
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://mmimagebuilder.blob.core.windows.net/windows-ami-builder/package/nxlog-ce-2.10.2150.msi
- name: papertrail-bundle.pem
  savepath: Windows\Temp\papertrail-bundle.pem
  unattend:
      - description: install papertrail certificate
        # yamllint disable-line rule:line-length
        command: cmd /c move /y C:\Windows\Temp\papertrail-bundle.pem "C:\Program Files\nxlog\cert\papertrail-bundle.pem"
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
      gpu:
          - true
          - false
  sources:
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://raw.githubusercontent.com/mozilla-releng/OpenCloudConfig/master/userdata/Configuration/nxlog/papertrail-bundle.pem
- name: papertrail-bundle.pem
  savepath: Windows\Temp\papertrail-bundle.pem
  unattend:
      - description: install papertrail certificate
        # yamllint disable-line rule:line-length
        command: cmd /c move /y C:\Windows\Temp\papertrail-bundle.pem "C:\Program Files (x86)\nxlog\cert\papertrail-bundle.pem"
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://raw.githubusercontent.com/mozilla-releng/OpenCloudConfig/master/userdata/Configuration/nxlog/papertrail-bundle.pem
- name: nxlog.conf
  savepath: Windows\Temp\nxlog.conf
  unattend:
      - description: stop nxlog service
        command: cmd /c net stop nxlog
      - description: install nxlog configuration
        # yamllint disable-line rule:line-length
        command: cmd /c set COPYCMD=/Y && move /y C:\Windows\Temp\nxlog.conf "C:\Program Files\nxlog\conf\nxlog.conf"
      - description: start nxlog service
        command: cmd /c net start nxlog
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
      gpu:
          - true
          - false
  sources:
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://raw.githubusercontent.com/mozilla-releng/OpenCloudConfig/master/userdata/Configuration/nxlog/win7.conf
- name: nxlog.conf
  savepath: Windows\Temp\nxlog.conf
  unattend:
      - description: stop nxlog service
        command: cmd /c net stop nxlog
      - description: install nxlog configuration
        # yamllint disable-line rule:line-length
        command: cmd /c set COPYCMD=/Y && move /y C:\Windows\Temp\nxlog.conf "C:\Program Files (x86)\nxlog\conf\nxlog.conf"
      - description: start nxlog service
        command: cmd /c net start nxlog
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 10
      architecture:
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://raw.githubusercontent.com/mozilla-releng/OpenCloudConfig/master/userdata/Configuration/nxlog/win10.conf
- name: nxlog.conf
  savepath: Windows\Temp\nxlog.conf
  unattend:
      - description: stop nxlog service
        command: cmd /c net stop nxlog
      - description: install nxlog configuration
        # yamllint disable-line rule:line-length
        command: cmd /c set COPYCMD=/Y && move /y C:\Windows\Temp\nxlog.conf "C:\Program Files (x86)\nxlog\conf\nxlog.conf"
      - description: start nxlog service
        command: cmd /c net start nxlog
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows Server 2012 R2
      architecture:
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://raw.githubusercontent.com/mozilla-releng/OpenCloudConfig/master/userdata/Configuration/nxlog/win2012.conf
- name: nxlog.conf
  savepath: Windows\Temp\nxlog.conf
  unattend:
      - description: stop nxlog service
        command: cmd /c net stop nxlog
      - description: install nxlog configuration
        # yamllint disable-line rule:line-length
        command: cmd /c set COPYCMD=/Y && move /y C:\Windows\Temp\nxlog.conf "C:\Program Files (x86)\nxlog\conf\nxlog.conf"
      - description: start nxlog service
        command: cmd /c net start nxlog
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows Server 2016
      architecture:
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://raw.githubusercontent.com/mozilla-releng/OpenCloudConfig/master/userdata/Configuration/nxlog/win2016.conf
- name: nxlog.conf
  savepath: Windows\Temp\nxlog.conf
  unattend:
      - description: stop nxlog service
        command: cmd /c net stop nxlog
      - description: install nxlog configuration
        # yamllint disable-line rule:line-length
        command: cmd /c set COPYCMD=/Y && move /y C:\Windows\Temp\nxlog.conf "C:\Program Files (x86)\nxlog\conf\nxlog.conf"
      - description: start nxlog service
        command: cmd /c net start nxlog
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows Server 2019
      architecture:
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://raw.githubusercontent.com/mozilla-releng/OpenCloudConfig/master/userdata/Configuration/nxlog/win2019.conf
- name: EC2Install.zip
  savepath: Windows\Temp
  unattend:
      - description: install ec2config
        command: cmd /c start /wait C:\Windows\Temp\Ec2Install.exe /quiet
  extract: true
  target:
      cloud:
          - amazon
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: amazon
        bucket: windows-ami-builder
        key: package/EC2Install.zip
- name: Ec2ConfigurationSettings.xml
  savepath: Windows\Temp\Ec2ConfigurationSettings.xml
  unattend:
      - description: install ec2config configuration
        # yamllint disable-line rule:line-length
        command: cmd /c move /y C:\Windows\Temp\Ec2ConfigurationSettings.xml "C:\Program Files\Amazon\Ec2ConfigService\Settings\config.xml"
  target:
      cloud:
          - amazon
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: amazon
        bucket: windows-ami-builder
        key: config/Ec2ConfigurationSettings.xml
- name: WallpaperSettings.xml
  savepath: Windows\Temp\WallpaperSettings.xml
  unattend:
      - description: install ec2 wallpaper configuration
        # yamllint disable-line rule:line-length
        command: cmd /c move /y C:\Windows\Temp\Ec2ConfigurationSettings.xml "C:\Program Files\Amazon\Ec2ConfigService\Settings\WallpaperSettings.xml"
  target:
      cloud:
          - amazon
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: amazon
        bucket: windows-ami-builder
        key: config/WallpaperSettings.xml
- name: WindowsAzureVmAgent.msi
  savepath: Windows\Temp\WindowsAzureVmAgent.msi
  unattend:
      - description: create log folder
        command: cmd /c if not exist C:\log mkdir C:\log
      - description: install azure agent
        # yamllint disable-line rule:line-length
        command: cmd /c start /wait msiexec /i C:\Windows\Temp\WindowsAzureVmAgent.msi /q /L*v C:\log\unattend-install-vmagent-stdout.log
  target:
      cloud:
          - azure
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: amazon
        bucket: windows-ami-builder
        key: package/WindowsAzureVmAgent.2.7.41491.949_191001-1418.fre.msi
      - platform: google
        bucket: windows-ami-builder
        key: package/WindowsAzureVmAgent.2.7.41491.949_191001-1418.fre.msi
      - platform: azure
        bucket: windows-ami-builder
        key: package/WindowsAzureVmAgent.2.7.41491.949_191001-1418.fre.msi
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://mmimagebuilder.blob.core.windows.net/windows-ami-builder/package/WindowsAzureVmAgent.2.7.41491.949_191001-1418.fre.msi
      - platform: url
        url: https://go.microsoft.com/fwlink/?LinkID=394789
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://download.microsoft.com/download/3/4/3/3437907D-745F-46EF-8116-7FC025BBEBDB/WindowsAzureVmAgent.2.7.41491.949_191001-1418.fre.msi
- name: psget-modules.zip
  savepath: Windows\System32\WindowsPowerShell\v1.0\Modules
  unattend: []
  extract: true
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows Server 2012 R2
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
  sources:
      - platform: amazon
        bucket: windows-ami-builder
        key: package/psget-modules.zip
- name: OpenCloudConfig
  savepath: Windows\Temp\rundsc.ps1
  unattend:
      - description: create log folder
        command: cmd /c if not exist C:\log mkdir C:\log
      - description: create dsc folder
        command: cmd /c if not exist C:\dsc mkdir C:\dsc
      - description: install occ trigger script
        command: cmd /c move /y C:\Windows\Temp\rundsc.ps1 C:\dsc\rundsc.ps1
      - description: create occ scheduled task
        # yamllint disable-line rule:line-length
        command: schtasks /create /tn RunDesiredStateConfigurationAtStartup /sc onstart /ru SYSTEM /rl HIGHEST /tr "powershell -ExecutionPolicy Bypass -NoLogo -NoProfile -File C:\dsc\rundsc.ps1" /f
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
      gpu:
          - true
          - false
  sources:
      - platform: url
        # yamllint disable-line rule:line-length
        url: https://raw.githubusercontent.com/mozilla-releng/OpenCloudConfig/master/userdata/rundsc.ps1
- name: dotNetFx45_Full_setup.exe
  savepath: Windows\Temp\dotNetFx45_Full_setup.exe
  unattend:
      - description: create dotNetFx45 log folder
        command: cmd /c if not exist C:\log\dotNetFx45 mkdir C:\log\dotNetFx45
      - description: extract powershell 5.1 cab files
        # yamllint disable-line rule:line-length
        command: cmd /c start /wait C:\Windows\Temp\dotNetFx45_Full_setup.exe /q /norestart /x86 /log C:\log\dotNetFx45
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
      gpu:
          - true
          - false
  sources:
      - platform: amazon
        bucket: windows-ami-builder
        key: package/dotNetFx45_Full_setup.exe
- name: Win7-KB3191566-x86.msu
  savepath: Windows\Temp\Win7-KB3191566-x86.msu
  unattend:
      - description: create extraction folder
        # yamllint disable-line rule:line-length
        command: cmd /c if not exist C:\Windows\Temp\wmf51 mkdir C:\Windows\Temp\wmf51
      - description: empty extraction folder
        command: cmd /c del /q C:\Windows\Temp\wmf51\*
      - description: extract powershell 5.1 cab files
        # yamllint disable-line rule:line-length
        command: cmd /c start /wait expand -F:* C:\Windows\Temp\Win7-KB3191566-x86.msu C:\Windows\Temp\wmf51
      - description: install kb2872035
        # yamllint disable-line rule:line-length
        command: cmd /c start /wait dism /Online /Add-Package /PackagePath:C:\Windows\Temp\wmf51\Windows6.1-KB2872035-x86.cab /Quiet /LogPath:C:\log\unattend-dism-kb2872035-stdout.log /NoRestart
      - description: install kb2872047
        # yamllint disable-line rule:line-length
        command: cmd /c start /wait dism /Online /Add-Package /PackagePath:C:\Windows\Temp\wmf51\Windows6.1-KB2872047-x86.cab /Quiet /LogPath:C:\log\unattend-dism-kb2872047-stdout.log /NoRestart
      - description: install kb3033929
        # yamllint disable-line rule:line-length
        command: cmd /c start /wait dism /Online /Add-Package /PackagePath:C:\Windows\Temp\wmf51\Windows6.1-KB3033929-x86.cab /Quiet /LogPath:C:\log\unattend-dism-kb3033929-stdout.log /NoRestart
      - description: install kb3191566
        # yamllint disable-line rule:line-length
        command: cmd /c start /wait dism /Online /Add-Package /PackagePath:C:\Windows\Temp\wmf51\Windows6.1-KB3191566-x86.cab /Quiet /LogPath:C:\log\unattend-dism-kb3191566-stdout.log
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
      gpu:
          - true
          - false
  sources:
      - platform: amazon
        bucket: windows-ami-builder
        key: package/Win7-KB3191566-x86.msu
