---
- description: create log folder
  command: cmd /c mkdir C:\log
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: enable rdp firewall exception
  command: >-
      netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes
      > C:\log\unattend-enable-rdp-firewall-exception-stdout.log 2>
      C:\log\unattend-enable-rdp-firewall-exception-stderr.log
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          # - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: disable network profile prompt
  command: >-
      reg add HKLM\System\CurrentControlSet\Control\Network\NewNetworkWindowOff
      > C:\log\unattend-disable-network-profile-prompt-stdout.log 2>
      C:\log\unattend-disable-network-profile-prompt-stderr.log
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: activate high performance power profile
  command: >-
      powercfg -setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c >
      C:\log\unattend-activate-power-profile-stdout.log 2>
      C:\log\unattend-activate-power-profile-stderr.log
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: disable ac power saving
  command: >-
      powercfg -change -monitor-timeout-ac 0 >
      C:\log\unattend-disable-ac-power-saving-stdout.log 2>
      C:\log\unattend-disable-ac-power-saving-stderr.log
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: disable dc power saving
  command: >-
      powercfg -change -monitor-timeout-dc 0 >
      C:\log\unattend-disable-dc-power-saving-stdout.log 2>
      C:\log\unattend-disable-dc-power-saving-stderr.log
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: remove proxy
  command: >-
      netsh winhttp reset proxy 0 >
      C:\log\unattend-remove-proxy-stdout.log 2>
      C:\log\unattend-remove-proxy-stderr.log
  target:
      cloud:
          - azure
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: activate high performance power profile
  command: >-
      powercfg /setactive SCHEME_MIN >
      C:\log\unattend-activate-power-profile-stdout.log 2>
      C:\log\unattend-activate-power-profile-stderr.log
  target:
      cloud:
          - azure
      os:
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: >-
      enable windows firewall for all profiles (domain, public, private)
  command: >-
      netsh advfirewall set allprofiles state on >
      C:\log\unattend-enable-windows-firewall-stdout.log 2>
      C:\log\unattend-enable-windows-firewall-stderr.log
  target:
      cloud:
          - azure
      os:
          # - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: enable winrm on windows 7
  # yamllint disable-line rule:line-length
  command: powershell -ExecutionPolicy Bypass -NoProfile -Command "Invoke-Expression -Command (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/mozilla-platform-ops/cloud-image-builder/master/scripts/enable-winrm.ps1');" > C:\log\unattend-enable-winrm-stdout.log 2> C:\log\unattend-enable-winrm-stderr.log
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
# - description: firewall allow inbound winrm over http
# yamllint disable-line rule:line-length
#   command: cmd /c netsh advfirewall firewall add rule name="Windows Remote Management (HTTP-In)" dir=in action=allow protocol=TCP localport=5985 profile=public > C:\log\unattend-firewall-allow-inbound-winrm-over-http-stdout.log 2> C:\log\unattend-firewall-allow-inbound-winrm-over-http-stderr.log
#   target:
#     cloud:
#       - azure
#     os:
#       - Windows 7
#     architecture:
#       - x86
#       - x86-64
#     gpu:
#       - true
#       - false
# - description: enable powershell remoting (winrm) over http
#   command: >-
#       winrm quickconfig -quiet -transport:http -force >
#       C:\log\unattend-enable-winrm-http-stdout.log 2>
#       C:\log\unattend-enable-winrm-http-stderr.log
#   target:
#       cloud:
#           - azure
#       os:
#           - Windows 8.1
#           - Windows 10
#           - Windows Server 2012 R2
#           - Windows Server 2016
#           - Windows Server 2019
#           - Windows Server
#       architecture:
#           - x86
#           - x86-64
#       gpu:
#           - true
#           - false
# - description: enable remote management firewall exception
# yamllint disable-line rule:line-length
#   command: cmd /c netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" new enable=yes remoteip=any > C:\log\unattend-enable-winrm-firewall-exception-stdout.log 2> C:\log\unattend-enable-winrm-firewall-exception-stderr.log
#   target:
#     cloud:
#       - azure
#     os:
#       - Windows 8.1
#       - Windows 10
#       - Windows Server 2012 R2
#       - Windows Server 2016
#       - Windows Server 2019
#       - Windows Server
#     architecture:
#       - x86
#       - x86-64
#     gpu:
#       - true
#       - false
- description: >-
    enable file and printer sharing firewall exception
    (allows icmp response on azure vnet)
  # yamllint disable-line rule:line-length
  command: netsh advfirewall firewall set rule name="File and Printer Sharing (Echo Request - ICMPv4-In)" new enable=yes > C:\log\unattend-enable-file-printer-sharing-firewall-exception-stdout.log 2> C:\log\unattend-enable-file-printer-sharing-firewall-exception-stderr.log
  target:
      cloud:
          - azure
      os:
          # - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
