---
- description: create log folder
  command: cmd /c mkdir C:\log
  target:
    cloud:
      - amazon
      - azure
      - google
    os:
      - Windows 7
      - Windows 8.1
      - Windows 10
      - Windows Server 2012 R2
      - Windows Server 2016
      - Windows Server 2019
      - Windows Server
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: enable remote desktop firewall exception
  # yamllint disable-line rule:line-length
  command: cmd /c netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes > C:\log\unattend-enable-rdp-firewall-exception-stdout.log 2> C:\log\unattend-enable-rdp-firewall-exception-stderr.log
  target:
    cloud:
      - amazon
      - azure
      - google
    os:
      - Windows 7
      - Windows 8.1
      - Windows 10
      - Windows Server 2012 R2
      - Windows Server 2016
      - Windows Server 2019
      - Windows Server
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: disable set-network-location prompt
  # yamllint disable-line rule:line-length
  command: reg add "HKLM\System\CurrentControlSet\Control\Network\NewNetworkWindowOff" > C:\log\unattend-disable-set-network-location-prompt-stdout.log 2> C:\log\unattend-disable-set-network-location-prompt-stderr.log
  target:
    cloud:
      - amazon
      - azure
      - google
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: set power profile to high performance
  command: cmd /c powercfg -setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c > C:\log\unattend-set-high-performance-power-profile-stdout.log 2> C:\log\unattend-set-high-performance-power-profile-stderr.log
  target:
    cloud:
      - amazon
      - azure
      - google
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: turn off ac power saving timeout
  command: cmd /c powercfg -change -monitor-timeout-ac 0 > C:\log\unattend-disable-ac-power-saving-stdout.log 2> C:\log\unattend-disable-ac-power-saving-stderr.log
  target:
    cloud:
      - amazon
      - azure
      - google
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: turn off dc power saving timeout
  command: cmd /c powercfg -change -monitor-timeout-dc 0 > C:\log\unattend-disable-dc-power-saving-stdout.log 2> C:\log\unattend-disable-dc-power-saving-stderr.log
  target:
    cloud:
      - amazon
      - azure
      - google
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: remove winhttp proxy
  command: cmd /c netsh winhttp reset proxy > C:\log\unattend-remove-winhttp-proxy-stdout.log 2> C:\log\unattend-remove-winhttp-proxy-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
      - Windows 8.1
      - Windows 10
      - Windows Server 2012 R2
      - Windows Server 2016
      - Windows Server 2019
      - Windows Server
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: set power profile to high performance
  command: cmd /c powercfg /setactive SCHEME_MIN > C:\log\unattend-set-high-performance-power-profile-stdout.log 2> C:\log\unattend-set-high-performance-power-profile-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 8.1
      - Windows 10
      - Windows Server 2012 R2
      - Windows Server 2016
      - Windows Server 2019
      - Windows Server
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: >-
      enable windows firewall for all profiles (domain, public, private)
  command: cmd /c netsh advfirewall set allprofiles state on > C:\log\unattend-enable-all-firewall-profiles-stdout.log 2> C:\log\unattend-enable-all-firewall-profiles-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
      - Windows 8.1
      - Windows 10
      - Windows Server 2012 R2
      - Windows Server 2016
      - Windows Server 2019
      - Windows Server
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: set network connection category
  # yamllint disable-line rule:line-length
  command: cmd /c powershell -NoProfile -Command "([Activator]::CreateInstance([Type]::GetTypeFromCLSID('DCB00C01-570F-4A9B-8D69-199FDBA5723B'))).GetNetworkConnections() | % { $_.GetNetwork().SetCategory(1) } 2> C:\log\unattend-set-network-connection-category-stderr.log"
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: winrm quickconfig -q
  command: cmd /c winrm quickconfig -q > C:\log\unattend-winrm-quickconfig-stdout.log 2> C:\log\unattend-winrm-quickconfig-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: winrm quickconfig -transport:http
  command: cmd /c winrm quickconfig -transport:http > C:\log\unattend-winrm-quickconfig-transport-http-stdout.log 2> C:\log\unattend-winrm-quickconfig-transport-http-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: winrm set winrm/config @{MaxTimeoutms="1800000"}
  command: cmd /c winrm set winrm/config @{MaxTimeoutms="1800000"} > C:\log\unattend-winrm-set-max-timeout-stdout.log 2> C:\log\unattend-winrm-set-max-timeout-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: winrm set winrm/config/winrs @{MaxMemoryPerShellMB="2048"}
  command: cmd /c winrm set winrm/config/winrs @{MaxMemoryPerShellMB="2048"} > C:\log\unattend-winrm-set-max-shell-memory-stdout.log 2> C:\log\unattend-winrm-set-max-shell-memory-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: winrm set winrm/config/service @{AllowUnencrypted="true"}
  command: cmd /c winrm set winrm/config/service @{AllowUnencrypted="true"} > C:\log\unattend-winrm-set-allow-unencrypted-stdout.log 2> C:\log\unattend-winrm-set-allow-unencrypted-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: winrm set winrm/config/service/auth @{Basic="true"}
  command: cmd /c winrm set winrm/config/service/auth @{Basic="true"} > C:\log\unattend-winrm-set-service-basic-auth-stdout.log 2> C:\log\unattend-winrm-set-service-basic-auth-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: winrm set winrm/config/client/auth @{Basic="true"}
  command: cmd /c winrm set winrm/config/client/auth @{Basic="true"} > C:\log\unattend-winrm-set-client-basic-auth-stdout.log 2> C:\log\unattend-winrm-set-client-basic-auth-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
# yamllint disable-line rule:line-length
- description: winrm set winrm/config/listener?Address=*+Transport=HTTP @{Port="5985"}
  # yamllint disable-line rule:line-length
  command: cmd /c winrm set winrm/config/listener?Address=*+Transport=HTTP @{Port="5985"} > C:\log\unattend-winrm-set-listener-port-stdout.log 2> C:\log\unattend-winrm-set-listener-port-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: winrm set winrm/config/client @{TrustedHosts="*"}
  command: cmd /c winrm set winrm/config/client @{TrustedHosts="*"} > C:\log\unattend-winrm-set-trusted-hosts-stdout.log 2> C:\log\unattend-winrm-set-trusted-hosts-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: firewall allow inbound winrm over http
  # yamllint disable-line rule:line-length
  command: cmd /c netsh advfirewall firewall add rule group="Windows Remote Management (HTTP-In)" dir=in action=allow protocol=TCP localport=5985 > C:\log\unattend-firewall-allow-inbound-winrm-over-http-stdout.log 2> C:\log\unattend-firewall-allow-inbound-winrm-over-http-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: firewall allow inbound winrm over https
  # yamllint disable-line rule:line-length
  command: cmd /c netsh advfirewall firewall add rule group="Windows Remote Management (HTTPS-In)" dir=in action=allow protocol=TCP localport=5985 > C:\log\unattend-firewall-allow-inbound-winrm-over-https-stdout.log 2> C:\log\unattend-firewall-allow-inbound-winrm-over-https-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: net stop winrm
  command: cmd /c net stop winrm
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: sc config winrm start= auto
  command: cmd /c sc config winrm start= auto > C:\log\unattend-sc-config-winrm-start-auto-stdout.log 2> C:\log\unattend-sc-config-winrm-start-auto-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: net start winrm
  command: cmd /c net start winrm > C:\log\unattend-net-start-winrm-stdout.log 2> C:\log\unattend-net-start-winrm-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: enable powershell remoting
  command: cmd /c winrm quickconfig -quiet -transport:http -force > C:\log\unattend-enable-powershell-remoting-stdout.log 2> C:\log\unattend-enable-powershell-remoting-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 8.1
      - Windows 10
      - Windows Server 2012 R2
      - Windows Server 2016
      - Windows Server 2019
      - Windows Server
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: enable remote management firewall exception
  # yamllint disable-line rule:line-length
  command: cmd /c netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" new enable=yes remoteip=any > C:\log\unattend-enable-winrm-firewall-exception-stdout.log 2> C:\log\unattend-enable-winrm-firewall-exception-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 8.1
      - Windows 10
      - Windows Server 2012 R2
      - Windows Server 2016
      - Windows Server 2019
      - Windows Server
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
- description: >-
    enable file and printer sharing firewall exception
    (allows icmp response on azure vnet)
  # yamllint disable-line rule:line-length
  command: cmd /c netsh advfirewall firewall set rule name="File and Printer Sharing (Echo Request - ICMPv4-In)" new enable=yes' > C:\log\unattend-enable-file-printer-sharing-firewall-exception-stdout.log 2> C:\log\unattend-enable-file-printer-sharing-firewall-exception-stderr.log
  target:
    cloud:
      - azure
    os:
      - Windows 7
      - Windows 8.1
      - Windows 10
      - Windows Server 2012 R2
      - Windows Server 2016
      - Windows Server 2019
      - Windows Server
    architecture:
      - x86
      - x86-64
    gpu:
      - true
      - false
