---
- description: disable network profile prompt
  # yamllint disable-line rule:line-length
  command: reg add HKLM\System\CurrentControlSet\Control\Network\NewNetworkWindowOff
  pass: auditUser
  synchronicity: asynchronous
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: remove proxy
  command: cmd /c start /wait netsh winhttp reset proxy 0
  pass: auditUser
  synchronicity: asynchronous
  target:
      cloud:
          - azure
      os:
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: activate high performance power profile
  command: cmd /c start /wait powercfg -setactive SCHEME_MIN
  pass: auditUser
  synchronicity: asynchronous
  target:
      cloud:
          - azure
      os:
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: disable ac power saving
  command: cmd /c start /wait powercfg -change -monitor-timeout-ac 0
  pass: auditUser
  synchronicity: asynchronous
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: disable dc power saving
  command: cmd /c start /wait powercfg -change -monitor-timeout-dc 0
  pass: auditUser
  synchronicity: asynchronous
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: >-
      enable windows firewall for all profiles (domain, public, private)
  command: cmd /c start /wait netsh advfirewall set allprofiles state on
  pass: auditUser
  synchronicity: asynchronous
  target:
      cloud:
          - azure
      os:
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: >-
    enable file and printer sharing firewall exception
    (allows icmp response on azure vnet)
  # yamllint disable-line rule:line-length
  command: cmd /c start /wait netsh advfirewall firewall set rule name="File and Printer Sharing (Echo Request - ICMPv4-In)" new enable=yes
  pass: auditUser
  synchronicity: asynchronous
  target:
      cloud:
          - azure
      os:
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: firewall create rule inbound winrm over http for public profile
  # yamllint disable-line rule:line-length
  command: cmd /c start /wait netsh advfirewall firewall add rule name="Windows Remote Management (HTTP-In)" dir=in action=allow protocol=TCP localport=5985 profile=public
  pass: auditUser
  synchronicity: asynchronous
  target:
      cloud:
          - azure
      os: []
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: firewall enable rule inbound winrm over http for all profiles
  # yamllint disable-line rule:line-length
  command: cmd /c start /wait netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" new enable=yes profile=any
  pass: auditUser
  synchronicity: asynchronous
  target:
      cloud:
          - azure
      os: []
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: enable rdp firewall exception
  # yamllint disable-line rule:line-length
  command: cmd /c start /wait netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes > C:\log\unattend-enable-rdp-firewall-exception-stdout.log 2> C:\log\unattend-enable-rdp-firewall-exception-stderr.log
  pass: auditUser
  synchronicity: asynchronous
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
# - description: disable firewall for all network profiles
#   command: >-
#       netsh advfirewall set allprofiles state off >
#       C:\log\unattend-disable-firewall-stdout.log 2>
#       C:\log\unattend-disable-firewall-stderr.log
#   target:
#       cloud:
#           - azure
#       os:
#           - Windows 7
#       architecture:
#           - x86
#           - x86-64
#       gpu:
#           - true
#           - false
# - description: enable winrm on windows 7
# yamllint disable-line rule:line-length
#   command: powershell -ExecutionPolicy Bypass -NoProfile -Command "Invoke-Expression -Command (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/mozilla-platform-ops/cloud-image-builder/master/scripts/enable-winrm.ps1');" > C:\log\unattend-enable-winrm-stdout.log 2> C:\log\unattend-enable-winrm-stderr.log
#   target:
#       cloud:
#           - azure
#       os:
#           - Windows 7
#       architecture:
#           - x86
#           - x86-64
#       gpu:
#           - true
#           - false
# - description: enable powershell remoting (winrm) over http
#   command: >-
#       winrm quickconfig -quiet -transport:http -force >
#       C:\log\unattend-enable-winrm-http-stdout.log 2>
#       C:\log\unattend-enable-winrm-http-stderr.log
#   target:
#       cloud:
#           - azure
#       os:
#           - Windows 8.1
#           - Windows 10
#           - Windows Server 2012 R2
#           - Windows Server 2016
#           - Windows Server 2019
#           - Windows Server
#       architecture:
#           - x86
#           - x86-64
#       gpu:
#           - true
#           - false
# - description: enable remote management firewall exception
# yamllint disable-line rule:line-length
#   command: cmd /c netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" new enable=yes remoteip=any > C:\log\unattend-enable-winrm-firewall-exception-stdout.log 2> C:\log\unattend-enable-winrm-firewall-exception-stderr.log
#   target:
#     cloud:
#       - azure
#     os:
#       - Windows 8.1
#       - Windows 10
#       - Windows Server 2012 R2
#       - Windows Server 2016
#       - Windows Server 2019
#       - Windows Server
#     architecture:
#       - x86
#       - x86-64
#     gpu:
#       - true
#       - false
