---
- description: create log folder
  command: cmd /c mkdir C:\log
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: enable remote desktop firewall exception
  # yamllint disable-line rule:line-length
  command: netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          # - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: disable set-network-location prompt
  # yamllint disable-line rule:line-length
  command: reg add "HKLM\System\CurrentControlSet\Control\Network\NewNetworkWindowOff"
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: set power profile to high performance
  command: powercfg -setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: turn off ac power saving timeout
  command: powercfg -change -monitor-timeout-ac 0
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: turn off dc power saving timeout
  command: powercfg -change -monitor-timeout-dc 0
  target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: remove winhttp proxy
  command: netsh winhttp reset proxy
  target:
      cloud:
          - azure
      os:
          - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: set power profile to high performance
  command: powercfg /setactive SCHEME_MIN
  target:
      cloud:
          - azure
      os:
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: >-
      enable windows firewall for all profiles (domain, public, private)
  command: netsh advfirewall set allprofiles state on
  target:
      cloud:
          - azure
      os:
          # - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: set network connection category
  # yamllint disable-line rule:line-length
  command: powershell -NoProfile -Command "([Activator]::CreateInstance([Type]::GetTypeFromCLSID('DCB00C01-570F-4A9B-8D69-199FDBA5723B'))).GetNetworkConnections() | % { $_.GetNetwork().SetCategory(1) } 2> C:\log\unattend-set-network-connection-category-stderr.log"
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: winrm quickconfig -q
  command: winrm quickconfig -q
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: winrm quickconfig -transport:http
  command: winrm quickconfig -transport:http
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: winrm set winrm/config @{MaxTimeoutms="1800000"}
  command: winrm set winrm/config @{MaxTimeoutms="1800000"}
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: winrm set winrm/config/winrs @{MaxMemoryPerShellMB="2048"}
  command: winrm set winrm/config/winrs @{MaxMemoryPerShellMB="2048"}
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: winrm set winrm/config/service @{AllowUnencrypted='true'}
  command: winrm set winrm/config/service @{AllowUnencrypted='true'}
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: winrm set winrm/config/service/auth @{Basic="true"}
  command: winrm set winrm/config/service/auth @{Basic="true"}
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: winrm set winrm/config/client/auth @{Basic="true"}
  command: winrm set winrm/config/client/auth @{Basic="true"}
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: >-
      winrm set winrm/config/listener?Address=*+Transport=HTTP @{Port="5985"}
  # yamllint disable-line rule:line-length
  command: winrm set winrm/config/listener?Address=*+Transport=HTTP @{Port="5985"} > C:\log\unattend-winrm-set-listener-port-stdout.log 2> C:\log\unattend-winrm-set-listener-port-stderr.log
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: winrm set winrm/config/client @{TrustedHosts="*"}
  command: winrm set winrm/config/client @{TrustedHosts="*"}
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
# - description: firewall allow inbound winrm over http
# yamllint disable-line rule:line-length
#   command: cmd /c netsh advfirewall firewall add rule name="Windows Remote Management (HTTP-In)" dir=in action=allow protocol=TCP localport=5985 profile=public > C:\log\unattend-firewall-allow-inbound-winrm-over-http-stdout.log 2> C:\log\unattend-firewall-allow-inbound-winrm-over-http-stderr.log
#   target:
#     cloud:
#       - azure
#     os:
#       - Windows 7
#     architecture:
#       - x86
#       - x86-64
#     gpu:
#       - true
#       - false
- description: net stop winrm
  command: cmd /c net stop winrm
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: sc config winrm start= auto
  command: sc config winrm start= auto
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: net start winrm
  command: cmd /c net start winrm
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
# disabling the windows 7 firewall below is a hack to get winrm working after
# sysprep completes. it would be preferable to use a firewall exception for
# inbound tcp on port 5985 (winrm http) on the firewall public profile, but for
# some reason, that exception is not enough to allow inbound winrm connections.
# the firewall should be re-enabled as part of the bootstrap process and in any
# case, the azure security group firewalls remain in place, irrespective of
# local system firewall state.
- description: disable firewall
  command: netsh advfirewall set allprofiles state off
  target:
      cloud:
          - azure
      os:
          - Windows 7
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
- description: enable powershell remoting
  command: winrm quickconfig -quiet -transport:http -force
  target:
      cloud:
          - azure
      os:
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
# - description: enable remote management firewall exception
# yamllint disable-line rule:line-length
#   command: cmd /c netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" new enable=yes remoteip=any > C:\log\unattend-enable-winrm-firewall-exception-stdout.log 2> C:\log\unattend-enable-winrm-firewall-exception-stderr.log
#   target:
#     cloud:
#       - azure
#     os:
#       - Windows 8.1
#       - Windows 10
#       - Windows Server 2012 R2
#       - Windows Server 2016
#       - Windows Server 2019
#       - Windows Server
#     architecture:
#       - x86
#       - x86-64
#     gpu:
#       - true
#       - false
- description: >-
    enable file and printer sharing firewall exception
    (allows icmp response on azure vnet)
  # yamllint disable-line rule:line-length
  command: netsh advfirewall firewall set rule name="File and Printer Sharing (Echo Request - ICMPv4-In)" new enable=yes > C:\log\unattend-enable-file-printer-sharing-firewall-exception-stdout.log 2> C:\log\unattend-enable-file-printer-sharing-firewall-exception-stderr.log
  target:
      cloud:
          - azure
      os:
          # - Windows 7
          - Windows 8.1
          - Windows 10
          - Windows Server 2012 R2
          - Windows Server 2016
          - Windows Server 2019
          - Windows Server
      architecture:
          - x86
          - x86-64
      gpu:
          - true
          - false
