---
image:
  os: Windows 10
  edition: Professional
  language: en-US
  architecture: x86-64
  timezone: UTC
  hostname: '*'
  gpu: true
  owner: Mozilla RelOps
  organization: Mozilla Corporation
  partition: MBR
  format: VHD
  type: Fixed
  target:
    platform: amazon
    bucket: windows-ami-builder
iso:
  source:
    platform: amazon
    bucket: windows-ami-builder
    key: iso/en_windows_10_business_editions_version_1903_updated_sept_2019_x64_dvd_a10b235d.iso
  wimindex: 5
manager:
  pool:
  - domain: gecko-t
    variant: win10-64-gpu
    capacity:
      minimum: 0
      maximum: 1
    locations:
    - eastus
    owner: grenade@mozilla.com
    provider: azure
target:
- platform: azure
  group: rg-east-us-gecko-t
  region: East US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 6
    ram: 56
    format: Standard_NV{0}_Promo
  disk:
  - os: true
    source: windows10-professional-en-us-x86-64-gpu
    variant: ssd
    size: 64
  - os: false
    variant: ssd
    size: 128
  - os: false
    variant: ssd
    size: 128
  network:
    name: vn-east-us-gecko-t
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-east-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-gecko-t
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-t-win10-64-gpu-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: 7e9f65c