---
image:
    os: Windows Server 2012 R2
    edition: Datacenter
    language: en-US
    architecture: x86-64
    timezone: UTC
    hostname: 'cib-sha'
    gpu: false
    owner: Mozilla Infrastructure Operations
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
    rdp: true
    obfuscate: true
    reseal:
        mode: Audit
        shutdown: true
    generalize:
        mode: OOBE
        shutdown: true
    reboot: 12
    network:
        location: Home
        dns:
            domain: win2012.mozilla.com
            suffixes: null
            devolution: false
        interfaces:
            - alias: Local Area Connection
              dns:
                  domain: null
                  dynamic: false
                  register: false
                  search:
                      - '1.1.1.1'
                      - '1.0.0.1'
    disks:
        - id: 0
          wipe: true
          partitions:
              - id: 1
                type:
                    name: Primary
                    id: 0x27
                size: 100
                active: true
                format: NTFS
                label: System Reserved
              - id: 2
                type:
                    name: Primary
                extend: true
                active: true
                format: NTFS
                label: os
                letter: 'C'
        - id: 1
          wipe: true
          partitions:
              - id: 1
                type:
                    name: Primary
                extend: true
                active: true
                format: NTFS
                label: cache
                letter: 'Y'
        - id: 2
          wipe: true
          partitions:
              - id: 1
                type:
                    name: Primary
                extend: true
                active: true
                format: NTFS
                label: task
                letter: 'Z'
    target:
        platform: amazon
        bucket: windows-ami-builder
iso:
    source:
        platform: amazon
        bucket: windows-ami-builder
        key: iso/en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso
    wimindex: 4
manager:
    pool:
        - domain: gecko-1
          variant: win2012-azure
          capacity:
              minimum: 0
              maximum: 3
          timeout:
              registration: 3600
              reregistration: 86400
          locations:
              - centralus
              - northcentralus
              - southcentralus
              - eastus
              - eastus2
              - westus
          lifecycle: normal
          owner: grenade@mozilla.com
          provider: azure
          platform: azure
        - domain: gecko-3
          variant: win2012-azure
          capacity:
              minimum: 0
              maximum: 3
          timeout:
              registration: 3600
              reregistration: 86400
          locations:
              - centralus
          owner: grenade@mozilla.com
          provider: azure
          platform: azure
        - domain: mpd001-1
          variant: win2012-amazon
          capacity:
              minimum: 0
              maximum: 3
          timeout:
              registration: 3600
              reregistration: 86400
          locations:
              - centralus
          owner: grenade@mozilla.com
          provider: aws
          platform: amazon
        - domain: mpd001-3
          variant: win2012-amazon
          capacity:
              minimum: 0
              maximum: 3
          timeout:
              registration: 3600
              reregistration: 86400
          locations:
              - centralus
          owner: grenade@mozilla.com
          provider: aws
          platform: amazon
target:
    - platform: azure
      group: rg-central-us-gecko-1
      region: Central US
      hostname: &hostname
          format: cib-{0}
          slug:
              type: disk-image-sha
              length: 7
      machine: &machine
          cpu: 4
          ram: 16
          format: Standard_DS{0}_v2
      disk: &disk
          - os: true
            source: windowsserver2012r2-datacenter-en-us-x86-64
            variant: ssd
            size: 64
            caching: ReadWrite
            create: FromImage
          - os: false
            variant: ssd
            size: 128
          - os: false
            variant: ssd
            size: 128
      network:
          name: vn-central-us-gecko-1
          prefix: '10.0.0.0/24'
          dns: &dns
              - '1.1.1.1'
              - '1.0.0.1'
          subnet:
              name: sn-central-us-gecko-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-central-us-gecko-1
              rules: &rules
                  - name: allow-rdp
                    description: >-
                        allow: inbound tcp connections,
                        \ for: rdp,
                        \ from: allowlist,
                        \ to: any host,
                        \ on port: 3389
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 110
                    sourceAddressPrefix:
                        - 185.189.196.0/22  # grenade
                        - 185.236.154.128/25  # grenade
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange: 3389
                  - name: allow-ssh
                    description: >-
                        allow: inbound tcp connections,
                        \ for: ssh,
                        \ from: allowlist,
                        \ to: any host,
                        \ on port: 22
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 111
                    sourceAddressPrefix:
                        - 185.189.196.0/22  # grenade
                        - 185.236.154.128/25  # grenade
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange: 22
      tag: &tag-gecko-1
          - name: workerType
            value: gecko-1-b-win2012-azure
          - name: sourceOrganisation
            value: mozilla-releng
          - name: sourceRepository
            value: OpenCloudConfig
          - name: sourceRevision
            value: e783de3
          - name: sourceScript
            value: userdata/rundsc.ps1
          - name: deploymentId
            value: e783de3
      bootstrap: &bootstrap
          executions: []
    - platform: azure
      group: rg-east-us-gecko-1
      region: East US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-east-us-gecko-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-gecko-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-gecko-1
              rules: *rules
      tag: *tag-gecko-1
      bootstrap: *bootstrap
    - platform: azure
      group: rg-east-us-2-gecko-1
      region: East US 2
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-east-us-2-gecko-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-2-gecko-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-2-gecko-1
              rules: *rules
      tag: *tag-gecko-1
      bootstrap: *bootstrap
    - platform: azure
      group: rg-north-central-us-gecko-1
      region: North Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-north-central-us-gecko-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-north-central-us-gecko-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-north-central-us-gecko-1
              rules: *rules
      tag: *tag-gecko-1
      bootstrap: *bootstrap
    - platform: azure
      group: rg-south-central-us-gecko-1
      region: South Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-south-central-us-gecko-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-south-central-us-gecko-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-south-central-us-gecko-1
              rules: *rules
      tag: *tag-gecko-1
      bootstrap: *bootstrap
    - platform: azure
      group: rg-west-us-gecko-1
      region: West US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-west-us-gecko-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-west-us-gecko-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-west-us-gecko-1
              rules: *rules
      tag: *tag-gecko-1
      bootstrap: *bootstrap
    - platform: azure
      group: rg-central-us-gecko-3
      region: Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-central-us-gecko-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-central-us-gecko-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-central-us-gecko-3
              rules: *rules
      tag: &tag-gecko-3
          - name: workerType
            value: gecko-3-b-win2012-azure
          - name: sourceOrganisation
            value: mozilla-releng
          - name: sourceRepository
            value: OpenCloudConfig
          - name: sourceRevision
            value: e783de3
          - name: sourceScript
            value: userdata/rundsc.ps1
          - name: deploymentId
            value: e783de3
      bootstrap: *bootstrap
    - platform: azure
      group: rg-east-us-gecko-3
      region: East US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-east-us-gecko-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-gecko-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-gecko-3
              rules: *rules
      tag: *tag-gecko-3
      bootstrap: *bootstrap
    - platform: azure
      group: rg-east-us-2-gecko-3
      region: East US 2
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-east-us-2-gecko-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-2-gecko-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-2-gecko-3
              rules: *rules
      tag: *tag-gecko-3
      bootstrap: *bootstrap
    - platform: azure
      group: rg-north-central-us-gecko-3
      region: North Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-north-central-us-gecko-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-north-central-us-gecko-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-north-central-us-gecko-3
              rules: *rules
      tag: *tag-gecko-3
      bootstrap: *bootstrap
    - platform: azure
      group: rg-south-central-us-gecko-3
      region: South Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-south-central-us-gecko-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-south-central-us-gecko-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-south-central-us-gecko-3
              rules: *rules
      tag: *tag-gecko-3
      bootstrap: *bootstrap
    - platform: azure
      group: rg-west-us-gecko-3
      region: West US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-west-us-gecko-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-west-us-gecko-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-west-us-gecko-3
              rules: *rules
      tag: *tag-gecko-3
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-central-us-mpd001-1
      region: Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-central-us-mpd001-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-central-us-mpd001-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-central-us-mpd001-1
              rules: *rules
      tag: &tag-mpd001-1
          - name: workerType
            value: mpd001-1-b-win2012-amazon
          - name: sourceOrganisation
            value: mozilla-platform-ops
          - name: sourceRepository
            value: ronin_puppet
          - name: sourceRevision
            value: cloud_windows
          - name: sourceScript
            value: provisioners/windows/azure/azure-bootstrap.ps1
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-east-us-mpd001-1
      region: East US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-east-us-mpd001-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-mpd001-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-mpd001-1
              rules: *rules
      tag: *tag-mpd001-1
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-east-us-2-mpd001-1
      region: East US 2
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-east-us-2-mpd001-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-2-mpd001-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-2-mpd001-1
              rules: *rules
      tag: *tag-mpd001-1
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-north-central-us-mpd001-1
      region: North Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-north-central-us-mpd001-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-north-central-us-mpd001-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-north-central-us-mpd001-1
              rules: *rules
      tag: *tag-mpd001-1
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-south-central-us-mpd001-1
      region: South Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-south-central-us-mpd001-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-south-central-us-mpd001-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-south-central-us-mpd001-1
              rules: *rules
      tag: *tag-mpd001-1
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-west-us-mpd001-1
      region: West US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-west-us-mpd001-1
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-west-us-mpd001-1
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-west-us-mpd001-1
              rules: *rules
      tag: *tag-mpd001-1
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-central-us-mpd001-3
      region: Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-central-us-mpd001-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-central-us-mpd001-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-central-us-mpd001-3
              rules: *rules
      tag: &tag-mpd001-3
          - name: workerType
            value: mpd001-3-b-win2012-amazon
          - name: sourceOrganisation
            value: mozilla-platform-ops
          - name: sourceRepository
            value: ronin_puppet
          - name: sourceRevision
            value: cloud_windows
          - name: sourceScript
            value: provisioners/windows/azure/azure-bootstrap.ps1
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-east-us-mpd001-3
      region: East US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-east-us-mpd001-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-mpd001-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-mpd001-3
              rules: *rules
      tag: *tag-mpd001-3
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-east-us-2-mpd001-3
      region: East US 2
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-east-us-2-mpd001-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-2-mpd001-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-2-mpd001-3
              rules: *rules
      tag: *tag-mpd001-3
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-north-central-us-mpd001-3
      region: North Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-north-central-us-mpd001-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-north-central-us-mpd001-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-north-central-us-mpd001-3
              rules: *rules
      tag: *tag-mpd001-3
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-south-central-us-mpd001-3
      region: South Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-south-central-us-mpd001-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-south-central-us-mpd001-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-south-central-us-mpd001-3
              rules: *rules
      tag: *tag-mpd001-3
      bootstrap: *bootstrap
    - platform: amazon
      group: rg-west-us-mpd001-3
      region: West US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-west-us-mpd001-3
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-west-us-mpd001-3
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-west-us-mpd001-3
              rules: *rules
      tag: *tag-mpd001-3
      bootstrap: *bootstrap
validation:
    instance:
        log:
            - program: 'sysprep-setupact'
              # yamllint disable-line rule:line-length
              match: '\[audit\.exe\] Successfully launched Sysprep with command line \[C:\\Windows\\system32\\sysprep\\sysprep\.exe  \/Generalize \/oobe \/shutdown\]'
            - program: 'OpenCloudConfig'
              # yamllint disable-line rule:line-length
              match: 'Invoke-Shutdown :: sysprep state: IMAGE_STATE_UNDEPLOYABLE, returning control to sysprep with exit code: 0'
