---
image:
  os: Windows Server 2012 R2
  edition: Datacenter
  language: en-US
  architecture: x86-64
  timezone: UTC
  hostname: '*'
  gpu: false
  owner: Mozilla RelOps
  organization: Mozilla Corporation
  partition: MBR
  format: VHD
  type: Fixed
  target:
    platform: amazon
    bucket: windows-ami-builder
iso:
  source:
    platform: amazon
    bucket: windows-ami-builder
    key: iso/en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso
  wimindex: 4
manager:
  pool:
  - domain: gecko-1
    variant: win2012
    capacity:
      minimum: 0
      maximum: 3
    locations:
    - centralus
    - northcentralus
    - southcentralus
    - eastus
    - eastus2
    - westus
    owner: grenade@mozilla.com
    provider: azure
  - domain: gecko-3
    variant: win2012
    capacity:
      minimum: 0
      maximum: 3
    locations:
    - centralus
    owner: grenade@mozilla.com
    provider: azure
  - domain: mpd001-1
    variant: win2012
    capacity:
      minimum: 0
      maximum: 3
    locations:
    - centralus
    owner: grenade@mozilla.com
    provider: azure
  - domain: mpd001-3
    variant: win2012
    capacity:
      minimum: 0
      maximum: 3
    locations:
    - centralus
    owner: grenade@mozilla.com
    provider: azure
target:
- platform: azure
  group: rg-central-us-gecko-1
  region: Central US
  hostname: &hostname
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine: &machine
    cpu: 2
    ram: 16
    format: Standard_A{0}
  disk: &disk
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  - os: false
    variant: ssd
    size: 128
  - os: false
    variant: ssd
    size: 128
  network:
    name: vn-central-us-gecko-1
    prefix: '10.0.0.0/24'
    dns: &dns
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-central-us-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-central-us-gecko-1
      rules: &rules
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag: &tag-gecko-1
  - name: workerType
    value: gecko-1-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: 7e9f65c
  - name: deploymentId
    value: 7e9f65c
  bootstrap: &bootstrap
    executions:
    - name: create-registry-key-mozilla-generic-worker
      shell: azure-powershell
      commands:
      - New-Item -Path 'HKLM:\SOFTWARE' -Name 'Mozilla' -Force;
      - New-Item -Path 'HKLM:\SOFTWARE\Mozilla' -Name 'GenericWorker' -Force;
    - name: create-registry-value-mozilla-generic-worker-client-id
      shell: azure-powershell
      commands:
      - Set-ItemProperty -Path 'HKLM:\SOFTWARE\Mozilla\GenericWorker' -Name 'clientId' -Value 'azure/gecko-1/win2012-azure' -Type 'String';
    - name: create-registry-value-mozilla-generic-worker-access-token
      shell: azure-powershell
      commands:
      - format: Set-ItemProperty -Path 'HKLM:\SOFTWARE\Mozilla\GenericWorker' -Name 'accessToken' -Value '{0}' -Type 'String';
        tokens:
        - (Invoke-WebRequest -Uri 'http://taskcluster/secrets/v1/secret/project/relops/image-builder/dev' -UseBasicParsing | ConvertFrom-Json).secret.accessToken.production.azure.'gecko-1'.win2012
- platform: azure
  group: rg-east-us-gecko-1
  region: East US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-gecko-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-gecko-1
      rules: *rules
  tag: *tag-gecko-1
- platform: azure
  group: rg-east-us-2-gecko-1
  region: East US 2
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-2-gecko-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-2-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-2-gecko-1
      rules: *rules
  tag: *tag-gecko-1
- platform: azure
  group: rg-north-central-us-gecko-1
  region: North Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-north-central-us-gecko-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-north-central-us-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-north-central-us-gecko-1
      rules: *rules
  tag: *tag-gecko-1
- platform: azure
  group: rg-south-central-us-gecko-1
  region: South Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-south-central-us-gecko-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-south-central-us-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-south-central-us-gecko-1
      rules: *rules
  tag: *tag-gecko-1
- platform: azure
  group: rg-west-us-gecko-1
  region: West US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-west-us-gecko-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-west-us-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-west-us-gecko-1
      rules: *rules
  tag: *tag-gecko-1
- platform: azure
  group: rg-central-us-gecko-3
  region: Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-central-us-gecko-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-central-us-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-central-us-gecko-3
      rules: *rules
  tag: &tag-gecko-3
  - name: workerType
    value: gecko-3-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: 7e9f65c
  - name: deploymentId
    value: 7e9f65c
- platform: azure
  group: rg-east-us-gecko-3
  region: East US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-gecko-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-gecko-3
      rules: *rules
  tag: *tag-gecko-3
- platform: azure
  group: rg-east-us-2-gecko-3
  region: East US 2
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-2-gecko-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-2-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-2-gecko-3
      rules: *rules
  tag: *tag-gecko-3
- platform: azure
  group: rg-north-central-us-gecko-3
  region: North Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-north-central-us-gecko-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-north-central-us-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-north-central-us-gecko-3
      rules: *rules
  tag: *tag-gecko-3
- platform: azure
  group: rg-south-central-us-gecko-3
  region: South Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-south-central-us-gecko-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-south-central-us-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-south-central-us-gecko-3
      rules: *rules
  tag: *tag-gecko-3
- platform: azure
  group: rg-west-us-gecko-3
  region: West US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-west-us-gecko-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-west-us-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-west-us-gecko-3
      rules: *rules
  tag: *tag-gecko-3
- platform: azure
  group: rg-central-us-mpd001-1
  region: Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-central-us-mpd001-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-central-us-mpd001-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-central-us-mpd001-1
      rules: *rules
  tag: &tag-mpd001-1
  - name: workerType
    value: mpd001-1-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: 7e9f65c
- platform: azure
  group: rg-east-us-mpd001-1
  region: East US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-mpd001-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-mpd001-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-mpd001-1
      rules: *rules
  tag: *tag-mpd001-1
- platform: azure
  group: rg-east-us-2-mpd001-1
  region: East US 2
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-2-mpd001-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-2-mpd001-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-2-mpd001-1
      rules: *rules
  tag: *tag-mpd001-1
- platform: azure
  group: rg-north-central-us-mpd001-1
  region: North Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-north-central-us-mpd001-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-north-central-us-mpd001-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-north-central-us-mpd001-1
      rules: *rules
  tag: *tag-mpd001-1
- platform: azure
  group: rg-south-central-us-mpd001-1
  region: South Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-south-central-us-mpd001-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-south-central-us-mpd001-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-south-central-us-mpd001-1
      rules: *rules
  tag: *tag-mpd001-1
- platform: azure
  group: rg-west-us-mpd001-1
  region: West US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-west-us-mpd001-1
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-west-us-mpd001-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-west-us-mpd001-1
      rules: *rules
  tag: *tag-mpd001-1
- platform: azure
  group: rg-central-us-mpd001-3
  region: Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-central-us-mpd001-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-central-us-mpd001-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-central-us-mpd001-3
      rules: *rules
  tag: &tag-mpd001-3
  - name: workerType
    value: mpd001-3-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: 7e9f65c
- platform: azure
  group: rg-east-us-mpd001-3
  region: East US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-mpd001-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-mpd001-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-mpd001-3
      rules: *rules
  tag: *tag-mpd001-3
- platform: azure
  group: rg-east-us-2-mpd001-3
  region: East US 2
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-2-mpd001-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-2-mpd001-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-2-mpd001-3
      rules: *rules
  tag: *tag-mpd001-3
- platform: azure
  group: rg-north-central-us-mpd001-3
  region: North Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-north-central-us-mpd001-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-north-central-us-mpd001-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-north-central-us-mpd001-3
      rules: *rules
  tag: *tag-mpd001-3
- platform: azure
  group: rg-south-central-us-mpd001-3
  region: South Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-south-central-us-mpd001-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-south-central-us-mpd001-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-south-central-us-mpd001-3
      rules: *rules
  tag: *tag-mpd001-3
- platform: azure
  group: rg-west-us-mpd001-3
  region: West US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-west-us-mpd001-3
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-west-us-mpd001-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-west-us-mpd001-3
      rules: *rules
  tag: *tag-mpd001-3