---
image:
  os: Windows Server 2019
  edition: Datacenter
  language: en-US
  architecture: x86-64
  timezone: UTC
  hostname: '*'
  gpu: false
  owner: Mozilla RelOps
  organization: Mozilla Corporation
  partition: MBR
  format: VHD
  type: Fixed
  target:
    platform: amazon
    bucket: windows-ami-builder
iso:
  source:
    platform: amazon
    bucket: windows-ami-builder
    key: iso/en_windows_server_2019_updated_sept_2019_x64_dvd_199664ce.iso
  wimindex: 4
manager:
  pool:
  - domain: relops
    variant: win2019
    capacity:
      minimum: 0
      maximum: 2
    locations:
    - centralus
    lifecycle: normal
    owner: grenade@mozilla.com
    provider: azure
    platform: azure
target:
- platform: azure
  group: rg-central-us-relops
  region: Central US
  hostname: &hostname
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine: &machine
    cpu: 2
    ram: 4
    format: Standard_A{0}
  disk: &disk
  - os: true
    source: windowsserver2019-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  - os: false
    variant: ssd
    size: 128
  - os: false
    variant: ssd
    size: 128
  network:
    name: vn-central-us-relops
    prefix: '10.0.0.0/24'
    dns: &dns
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-central-us-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-central-us-relops
      rules: &rules
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag: &tag
  - name: workerType
    value: relops-win2019-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: 6b9700b
- platform: azure
  group: rg-east-us-relops
  region: East US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-relops
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-relops
      rules: *rules
  tag: *tag
- platform: azure
  group: rg-east-us-2-relops
  region: East US 2
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-2-relops
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-2-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-2-relops
      rules: *rules
  tag: *tag
- platform: azure
  group: rg-north-central-us-relops
  region: North Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-north-central-us-relops
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-north-central-us-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-north-central-us-relops
      rules: *rules
  tag: *tag
- platform: azure
  group: rg-south-central-us-relops
  region: South Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-south-central-us-relops
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-south-central-us-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-south-central-us-relops
      rules: *rules
  tag: *tag
- platform: azure
  group: rg-west-us-relops
  region: West US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-west-us-relops
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-west-us-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-west-us-relops
      rules: *rules
  tag: *tag