---
image:
  os: Windows Server 2019
  edition: Datacenter
  language: en-US
  architecture: x86-64
  timezone: UTC
  hostname: '*'
  gpu: false
  owner: Mozilla RelOps
  organization: Mozilla Corporation
  partition: MBR
  format: VHD
  type: Fixed
  target:
    platform: amazon
    bucket: windows-ami-builder
iso:
  source:
    platform: amazon
    bucket: windows-ami-builder
    key: iso/en_windows_server_2019_updated_sept_2019_x64_dvd_199664ce.iso
  wimindex: 4
manager:
  pool:
  - domain: relops
    variant: win2019
    capacity:
      minimum: 0
      maximum: 2
    locations:
    - centralus
    lifecycle: normal
    owner: grenade@mozilla.com
    provider: azure
    platform: azure
target:
- platform: azure
  group: rg-central-us-relops
  region: Central US
  hostname: &hostname
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine: &machine
    cpu: 2
    ram: 4
    format: Standard_A{0}
  disk: &disk
  - os: true
    source: windowsserver2019-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  - os: false
    variant: ssd
    size: 128
  - os: false
    variant: ssd
    size: 128
  network:
    name: vn-central-us-relops
    prefix: '10.0.0.0/24'
    dns: &dns
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-central-us-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-central-us-relops
      rules: &rules
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        protocol: Tcp
        direction: Inbound
        priority: 110
        sourceAddressPrefix:
        - 185.189.196.96/27
        - 185.189.196.128/25
        sourcePortRange: '*'
        destinationAddressPrefix: '*'
        destinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        protocol: Tcp
        direction: Inbound
        priority: 111
        sourceAddressPrefix:
        - 185.189.196.96/27
        - 185.189.196.128/25
        sourcePortRange: '*'
        destinationAddressPrefix: '*'
        destinationPortRange: 22
  tag: &tag
  - name: workerType
    value: relops-win2019-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: ca3c0aa
  - name: sourceScript
    value: userdata/rundsc.ps1
  - name: deploymentId
    value: ca3c0aa
  bootstrap: &bootstrap
    executions:
    # set hostname to match the azure machine name so that debug logs can be found in papertrail
    - name: set-computer-name
      shell: azure-powershell
      commands:
      - $instanceName = (((Invoke-WebRequest -Headers @{'Metadata'=$true} -UseBasicParsing -Uri 'http://169.254.169.254/metadata/instance?api-version=2019-06-04').Content) | ConvertFrom-Json).compute.name
      - '[Environment]::SetEnvironmentVariable("COMPUTERNAME", $instanceName, "Machine")'
      - $env:COMPUTERNAME = $instanceName
      - (Get-WmiObject Win32_ComputerSystem).Rename($instanceName) | Out-Null
      - if ([System.Net.Dns]::GetHostName() -eq $instanceName) { Write-Output -InputObject ('expected hostname detected'); exit 0; } else { Write-Output -InputObject ('host rename failure'); exit 1; }
      test:
        std:
          out:
            match: /expected hostname detected/
      on:
        success: reboot
    # set maintenance secrets in the windows registry
    - name: create-mozilla-registry-keys
      shell: azure-powershell
      commands:
      - New-Item -Path 'HKLM:\SOFTWARE' -Name 'Mozilla' -Force
      - New-Item -Path 'HKLM:\SOFTWARE\Mozilla' -Name 'GenericWorker' -Force
      - New-Item -Path 'HKLM:\SOFTWARE\Mozilla' -Name 'tooltool' -Force
    - name: create-registry-value-mozilla-generic-worker-client-id
      shell: azure-powershell
      commands:
      - Set-ItemProperty -Path 'HKLM:\SOFTWARE\Mozilla\GenericWorker' -Name 'clientId' -Value 'azure/relops/win2019-azure' -Type 'String';
    - name: create-registry-value-mozilla-generic-worker-access-token
      shell: azure-powershell
      commands:
      - format: Set-ItemProperty -Path 'HKLM:\SOFTWARE\Mozilla\GenericWorker' -Name 'accessToken' -Value '{0}' -Type 'String';
        tokens:
        - (Invoke-WebRequest -Uri 'http://taskcluster/secrets/v1/secret/project/relops/image-builder/dev' -UseBasicParsing | ConvertFrom-Json).secret.accessToken.production.azure.relops.'win2019-azure'
    - name: create-registry-value-mozilla-tooltool-access-token
      shell: azure-powershell
      commands:
      - format: Set-ItemProperty -Path 'HKLM:\SOFTWARE\Mozilla\tooltool' -Name 'accessToken' -Value '{0}' -Type 'String';
        tokens:
        - (Invoke-WebRequest -Uri 'http://taskcluster/secrets/v1/secret/project/relops/image-builder/dev' -UseBasicParsing | ConvertFrom-Json).secret.tooltoolToken.production.azure.relops.'win2019-azure'
    # trigger bootstrap script and await completion
    - name: invoke-occ
      shell: azure-powershell
      commands:
      - Invoke-Expression (New-Object Net.WebClient).DownloadString(('https://raw.githubusercontent.com/{0}/{1}/{2}/{3}?{4}' -f (@(((Invoke-WebRequest -Headers @{'Metadata'=$true} -UseBasicParsing -Uri ('http://169.254.169.254/metadata/instance?api-version={0}' -f '2019-06-04')).Content) | ConvertFrom-Json).compute.tagsList | ? { $_.name -eq 'sourceOrganisation' })[0].value, (@(((Invoke-WebRequest -Headers @{'Metadata'=$true} -UseBasicParsing -Uri ('http://169.254.169.254/metadata/instance?api-version={0}' -f '2019-06-04')).Content) | ConvertFrom-Json).compute.tagsList | ? { $_.name -eq 'sourceRepository' })[0].value, (@(((Invoke-WebRequest -Headers @{'Metadata'=$true} -UseBasicParsing -Uri ('http://169.254.169.254/metadata/instance?api-version={0}' -f '2019-06-04')).Content) | ConvertFrom-Json).compute.tagsList | ? { $_.name -eq 'sourceRevision' })[0].value, (@(((Invoke-WebRequest -Headers @{'Metadata'=$true} -UseBasicParsing -Uri ('http://169.254.169.254/metadata/instance?api-version={0}' -f '2019-06-04')).Content) | ConvertFrom-Json).compute.tagsList | ? { $_.name -eq 'sourceScript' })[0].value, [Guid]::NewGuid()))
    - name: verify-occ
      shell: azure-powershell
      commands:
      - if (Test-Path -Path 'C:\generic-worker\ed25519-private.key' -ErrorAction SilentlyContinue) { Write-Output -InputObject ('ed25519 private key detected') }
      test:
        std:
          out:
            match: /ed25519 private key detected/
      on:
        failure: retry
- platform: azure
  group: rg-east-us-relops
  region: East US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-relops
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-relops
      rules: *rules
  tag: *tag
  bootstrap: *bootstrap
- platform: azure
  group: rg-east-us-2-relops
  region: East US 2
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-2-relops
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-2-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-2-relops
      rules: *rules
  tag: *tag
  bootstrap: *bootstrap
- platform: azure
  group: rg-north-central-us-relops
  region: North Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-north-central-us-relops
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-north-central-us-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-north-central-us-relops
      rules: *rules
  tag: *tag
  bootstrap: *bootstrap
- platform: azure
  group: rg-south-central-us-relops
  region: South Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-south-central-us-relops
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-south-central-us-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-south-central-us-relops
      rules: *rules
  tag: *tag
  bootstrap: *bootstrap
- platform: azure
  group: rg-west-us-relops
  region: West US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-west-us-relops
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-west-us-relops
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-west-us-relops
      rules: *rules
  tag: *tag
  bootstrap: *bootstrap