---
image:
  os: Windows Server 2012 R2
  edition: Datacenter
  language: en-US
  architecture: x86-64
  gpu: false
  owner: Mozilla RelOps
  organization: Mozilla Corporation
  partition: MBR
  format: VHD
  type: Fixed
iso:
  source:
    platform: amazon
    bucket: windows-ami-builder
    key: iso/en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso
  wimindex: 4
target:
- platform: azure
  group: rg-central-us-gecko-1
  region: Central US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-central-us-gecko-1
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-central-us-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-central-us-gecko-1
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-1-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-east-us-gecko-1
  region: East US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-east-us-gecko-1
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-east-us-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-gecko-1
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-1-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-east-us-2-gecko-1
  region: East US 2
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-east-us-2-gecko-1
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-east-us-2-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-2-gecko-1
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-1-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-north-central-us-gecko-1
  region: North Central US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-north-central-us-gecko-1
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-north-central-us-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-north-central-us-gecko-1
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-1-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-south-central-us-gecko-1
  region: South Central US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-south-central-us-gecko-1
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-south-central-us-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-south-central-us-gecko-1
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-1-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-west-us-gecko-1
  region: West US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-west-us-gecko-1
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-west-us-gecko-1
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-west-us-gecko-1
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-1-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-central-us-gecko-3
  region: Central US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-central-us-gecko-3
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-central-us-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-central-us-gecko-3
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-3-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-east-us-gecko-3
  region: East US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-east-us-gecko-3
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-east-us-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-gecko-3
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-3-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-east-us-2-gecko-3
  region: East US 2
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-east-us-2-gecko-3
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-east-us-2-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-2-gecko-3
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-3-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-north-central-us-gecko-3
  region: North Central US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-north-central-us-gecko-3
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-north-central-us-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-north-central-us-gecko-3
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-3-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-south-central-us-gecko-3
  region: South Central US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-south-central-us-gecko-3
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-south-central-us-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-south-central-us-gecko-3
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-3-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure
- platform: azure
  group: rg-west-us-gecko-3
  region: West US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windowsserver2012r2-datacenter-en-us-x86-64
    variant: ssd
    size: 64
  network:
    name: vn-west-us-gecko-3
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-west-us-gecko-3
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-west-us-gecko-3
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-3-b-win2012-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: azure