---
image:
    os: Windows Server 2019
    edition: Datacenter
    language: en-US
    architecture: x86-64
    timezone: UTC
    hostname: 'cib-sha'
    gpu: false
    owner: Mozilla Infrastructure Operations
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
    size: 64
    rdp: true
    obfuscate: true
    reseal:
        mode: Audit
        shutdown: true
    generalize:
        mode: OOBE
        shutdown: true
    reboot: 9
    network:
        location: Home
        dns:
            domain: win2019.mozilla.com
            suffixes: null
            devolution: false
        interfaces:
            - alias: Local Area Connection
              dns:
                  domain: null
                  dynamic: false
                  register: false
                  search:
                      - '1.1.1.1'
                      - '1.0.0.1'
    disks:
        - id: 0
          wipe: true
          partitions:
              - id: 1
                type:
                    name: Primary
                    id: 0x27
                size: 100
                active: true
                format: NTFS
                label: System Reserved
              - id: 2
                type:
                    name: Primary
                extend: true
                active: true
                format: NTFS
                label: os
                letter: 'C'
        - id: 1
          wipe: true
          partitions:
              - id: 1
                type:
                    name: Primary
                extend: true
                active: true
                format: NTFS
                label: cache
                letter: 'Y'
        - id: 2
          wipe: true
          partitions:
              - id: 1
                type:
                    name: Primary
                extend: true
                active: true
                format: NTFS
                label: task
                letter: 'Z'
    target:
        platform: amazon
        bucket: windows-ami-builder
iso:
    source:
        platform: amazon
        bucket: windows-ami-builder
        key: iso/en_windows_server_2019_updated_sept_2019_x64_dvd_199664ce.iso
    wimindex: 4
manager:
    pool:
        - domain: relops
          variant: win2019-azure
          capacity:
              minimum: 0
              maximum: 2
          timeout:
              registration: 3600
              reregistration: 86400
          locations:
              - centralus
          lifecycle: spot
          owner: grenade@mozilla.com
          provider: azure
          platform: azure
target:
    - platform: azure
      group: rg-central-us-relops
      sourcePortRange: sacentralusrelops
      region: Central US
      hostname: &hostname
          format: cib-{0}
          slug:
              type: disk-image-sha
              length: 7
      machine: &machine
          cpu: 2
          ram: 4
          format: Standard_A{0}
          hyperv: V1
      disk: &disk
          - os: true
            source: windowsserver2019-datacenter-en-us-x86-64
            variant: ssd
            size: 64
            caching: ReadWrite
            create: FromImage
          - os: false
            variant: ssd
            size: 128
          - os: false
            variant: ssd
            size: 128
      network:
          name: vn-central-us-relops
          prefix: '10.0.0.0/24'
          dns: &dns
              - '1.1.1.1'
              - '1.0.0.1'
          subnet:
              name: sn-central-us-relops
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-central-us-relops
              rules: &rules
                  - name: allow-rdp
                    description: >-
                        allow: inbound tcp connections,
                        \ for: rdp,
                        \ from: allowlist,
                        \ to: any host,
                        \ on port: 3389
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 110
                    sourceAddressPrefix:
                        - 185.189.196.0/22  # grenade
                        - 185.236.154.128/25  # grenade
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange: 3389
                  - name: allow-ssh
                    description: >-
                        allow: inbound tcp connections,
                        \ for: ssh,
                        \ from: allowlist,
                        \ to: any host,
                        \ on port: 22
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 111
                    sourceAddressPrefix:
                        - 185.189.196.0/22  # grenade
                        - 185.236.154.128/25  # grenade
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange: 22
      tag: &tag
          - name: workerType
            value: relops-win2019-azure
          - name: sourceOrganisation
            value: mozilla-releng
          - name: sourceRepository
            value: OpenCloudConfig
          - name: sourceRevision
            value: 2facf4f
          - name: sourceScript
            value: userdata/rundsc.ps1
          - name: deploymentId
            value: 2facf4f
      bootstrap: &bootstrap
          executions: []
    - platform: azure
      group: rg-east-us-relops
      storage: saeastusrelops
      region: East US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-east-us-relops
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-relops
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-relops
              rules: *rules
      tag: *tag
      bootstrap: *bootstrap
    - platform: azure
      group: rg-east-us-2-relops
      storage: saeastus2relops
      region: East US 2
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-east-us-2-relops
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-2-relops
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-2-relops
              rules: *rules
      tag: *tag
      bootstrap: *bootstrap
    - platform: azure
      group: rg-north-central-us-relops
      storage: sanorthcentralusrelops
      region: North Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-north-central-us-relops
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-north-central-us-relops
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-north-central-us-relops
              rules: *rules
      tag: *tag
      bootstrap: *bootstrap
    - platform: azure
      group: rg-south-central-us-relops
      storage: sasouthcentralusrelops
      region: South Central US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-south-central-us-relops
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-south-central-us-relops
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-south-central-us-relops
              rules: *rules
      tag: *tag
      bootstrap: *bootstrap
    - platform: azure
      group: rg-west-us-relops
      storage: sawestusrelops
      region: West US
      hostname: *hostname
      machine: *machine
      disk: *disk
      network:
          name: vn-west-us-relops
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-west-us-relops
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-west-us-relops
              rules: *rules
      tag: *tag
      bootstrap: *bootstrap
validation:
    instance:
        log:
            - program: 'sysprep-setupact'
              # yamllint disable-line rule:line-length
              match: '\[audit\.exe\] Successfully launched Sysprep with command line \[C:\\Windows\\system32\\sysprep\\sysprep\.exe \/oobe \/shutdown \/Generalize\]'
            - program: 'OpenCloudConfig'
              # yamllint disable-line rule:line-length
              match: 'Invoke-Shutdown :: sysprep state: IMAGE_STATE_UNDEPLOYABLE, returning control to sysprep with exit code: 0'
