---
image:
    os: Windows 7
    edition: Professional
    language: en-US
    architecture: x86
    timezone: UTC
    hostname: '*'
    gpu: true
    owner: Mozilla Release Operations
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
    rdp: true
    target:
        platform: amazon
        bucket: windows-ami-builder
iso:
    source:
        platform: amazon
        bucket: windows-ami-builder
        key: iso/en_windows_7_professional_with_sp1_x86_dvd_u_677056.iso
    wimindex: 4
manager:
    pool:
        - domain: gecko-t
          variant: win7-32-gpu-azure
          capacity:
              minimum: 0
              maximum: 1
          timeout:
              registration: 3600
              reregistration: 86400
          locations:
              - eastus
          lifecycle: normal
          owner: grenade@mozilla.com
          provider: azure
          platform: azure
target:
    - platform: azure
      group: rg-east-us-gecko-t
      region: East US
      hostname:
          format: vm-{0}
          slug:
              type: uuid
              length: 12
      machine:
          cpu: 6
          ram: 56
          format: Standard_NV{0}_Promo
      disk:
          - os: true
            source: windows7-professional-en-us-x86-gpu
            variant: ssd
            size: 64
          - os: false
            variant: ssd
            size: 128
          - os: false
            variant: ssd
            size: 128
      network:
          name: vn-east-us-gecko-t
          prefix: '10.0.0.0/24'
          dns:
              - '1.1.1.1'
              - '1.0.0.1'
          subnet:
              name: sn-east-us-gecko-t
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-gecko-t
              rules:
                  - name: allow-rdp
                    description: >-
                        allow: inbound tcp connections,
                        \ for: rdp,
                        \ from: whitelist,
                        \ to: any host,
                        \ on port: 3389
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 110
                    sourceAddressPrefix:
                        # grenade - gnet, bulgaria
                        - 185.189.196.0/22
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange: 3389
                  - name: allow-ssh
                    description: >-
                        allow: inbound tcp connections,
                        \ for: ssh,
                        \ from: whitelist,
                        \ to: any host,
                        \ on port: 22
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 111
                    sourceAddressPrefix:
                        # grenade - gnet, bulgaria
                        - 185.189.196.0/22
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange: 22
                  - name: allow-winrm
                    description: >-
                        allow: inbound tcp connections,
                        \ for: winrm over http and https,
                        \ from: whitelist,
                        \ to: any host,
                        \ on ports: 5985, 5986
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 112
                    sourceAddressPrefix:
                        # grenade - gnet, bulgaria
                        - 185.189.196.0/22
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange:
                        - 5985
                        - 5986
      tag:
          - name: workerType
            value: gecko-t-win7-32-gpu-azure
          - name: sourceOrganisation
            value: mozilla-releng
          - name: sourceRepository
            value: OpenCloudConfig
          - name: sourceRevision
            value: 8e290d7
          - name: sourceScript
            value: userdata/rundsc.ps1
          - name: deploymentId
            value: 8e290d7
