---
image:
  os: Windows 7
  edition: Professional
  language: en-US
  architecture: x86
  timezone: UTC
  hostname: '*'
  gpu: false
  owner: Mozilla Release Operations
  organization: Mozilla Corporation
  partition: MBR
  format: VHD
  type: Fixed
  target:
    platform: amazon
    bucket: windows-ami-builder
iso:
  source:
    platform: amazon
    bucket: windows-ami-builder
    key: iso/en_windows_7_professional_with_sp1_x86_dvd_u_677056.iso
  wimindex: 4
target:
- platform: azure
  group: rg-central-us-gecko-t
  region: Central US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_F{0}s_v2
  disk:
  - os: true
    source: windows7-professional-en-us-x86
    variant: ssd
    size: 64
  network:
    name: vn-central-us-gecko-t
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-central-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-central-us-gecko-t
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-t-win7-32-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: a111be086b7b7d439f5ffb46a7b03560f502794e
- platform: azure
  group: rg-east-us-gecko-t
  region: East US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_A{0}
  disk:
  - os: true
    source: windows7-professional-en-us-x86
    variant: ssd
    size: 64
  network:
    name: vn-east-us-gecko-t
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-east-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-gecko-t
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-t-win7-32-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: a111be086b7b7d439f5ffb46a7b03560f502794e
- platform: azure
  group: rg-east-us-2-gecko-t
  region: East US 2
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_A{0}
  disk:
  - os: true
    source: windows7-professional-en-us-x86
    variant: ssd
    size: 64
  network:
    name: vn-east-us-2-gecko-t
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-east-us-2-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-2-gecko-t
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-t-win7-32-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: a111be086b7b7d439f5ffb46a7b03560f502794e
- platform: azure
  group: rg-north-central-us-gecko-t
  region: North Central US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_A{0}
  disk:
  - os: true
    source: windows7-professional-en-us-x86
    variant: ssd
    size: 64
  network:
    name: vn-north-central-us-gecko-t
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-north-central-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-north-central-us-gecko-t
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-t-win7-32-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: a111be086b7b7d439f5ffb46a7b03560f502794e
- platform: azure
  group: rg-south-central-us-gecko-t
  region: South Central US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_A{0}
  disk:
  - os: true
    source: windows7-professional-en-us-x86
    variant: ssd
    size: 64
  network:
    name: vn-south-central-us-gecko-t
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-south-central-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-south-central-us-gecko-t
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-t-win7-32-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: a111be086b7b7d439f5ffb46a7b03560f502794e
- platform: azure
  group: rg-west-us-gecko-t
  region: West US
  hostname:
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine:
    cpu: 2
    ram: 4
    format: Standard_A{0}
  disk:
  - os: true
    source: windows7-professional-en-us-x86
    variant: ssd
    size: 64
  network:
    name: vn-west-us-gecko-t
    prefix: '10.0.0.0/24'
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-west-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-west-us-gecko-t
      rules:
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 110
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        Protocol: Tcp
        Direction: Inbound
        Priority: 111
        SourceAddressPrefix:
        - 185.189.196.216
        SourcePortRange: '*'
        DestinationAddressPrefix: '*'
        DestinationPortRange: 22
  tag:
  - name: workerType
    value: gecko-t-win7-32-azure
  - name: sourceOrganisation
    value: mozilla-releng
  - name: sourceRepository
    value: OpenCloudConfig
  - name: sourceRevision
    value: a111be086b7b7d439f5ffb46a7b03560f502794e