---
image:
    os: Windows 7
    edition: Professional
    language: en-US
    architecture: x86
    timezone: UTC
    hostname: 'cib-sha'
    gpu: false
    owner: Mozilla Infrastructure Operations
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
    rdp: true
    obfuscate: true
    reseal:
        mode: Audit
        shutdown: true
    generalize:
        mode: OOBE
        shutdown: true
    reboot: 10
    network:
        location: Home
        dns:
            domain: win7-32.mozilla.com
            suffixes: null
            devolution: false
        interfaces:
            - alias: Local Area Connection
              dns:
                  domain: null
                  dynamic: false
                  register: false
                  search:
                      - '1.1.1.1'
                      - '1.0.0.1'
    disks:
        - id: 0
          wipe: true
          partitions:
              - id: 1
                type:
                    name: Primary
                    id: 0x27
                size: 100
                active: true
                format: NTFS
                label: System Reserved
              - id: 2
                type:
                    name: Primary
                extend: true
                active: true
                format: NTFS
                label: os
                letter: 'C'
        - id: 1
          wipe: true
          partitions:
              - id: 1
                type:
                    name: Primary
                extend: true
                active: true
                format: NTFS
                label: cache
                letter: 'Y'
        - id: 2
          wipe: true
          partitions:
              - id: 1
                type:
                    name: Primary
                extend: true
                active: true
                format: NTFS
                label: task
                letter: 'Z'
    target:
        platform: amazon
        bucket: windows-ami-builder
iso:
    source:
        platform: amazon
        bucket: windows-ami-builder
        key: iso/en_windows_7_professional_with_sp1_x86_dvd_u_677056.iso
    wimindex: 4
manager:
    pool:
        - domain: gecko-t
          variant: win7-32-azure
          capacity:
              minimum: 0
              maximum: 1
          timeout:
              registration: 3600
              reregistration: 86400
          locations:
              - centralus
              - northcentralus
              - southcentralus
              - eastus
              - eastus2
          lifecycle: spot
          owner: grenade@mozilla.com
          provider: azure
          platform: azure
target:
    - platform: azure
      group: rg-central-us-gecko-t
      region: Central US
      hostname: &hostname
          format: cib-{0}
          slug:
              type: disk-image-sha
              length: 7
      machine: &machine
          cpu: 2
          ram: 4
          format: Standard_F{0}s_v2
      agent: disable
      diagnostics: enable
      disk: &disk
          - os: true
            source: windows7-professional-en-us-x86
            variant: ssd
            size: 64
            caching: ReadWrite
            create: FromImage
          - os: false
            variant: ssd
            size: 128
          - os: false
            variant: ssd
            size: 128
      network:
          name: vn-central-us-gecko-t
          prefix: '10.0.0.0/24'
          dns: &dns
              - '1.1.1.1'
              - '1.0.0.1'
          subnet:
              name: sn-central-us-gecko-t
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-central-us-gecko-t
              rules: &rules
                  - name: allow-rdp
                    description: >-
                        allow: inbound tcp connections,
                        \ for: rdp,
                        \ from: allowlist,
                        \ to: any host,
                        \ on port: 3389
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 110
                    sourceAddressPrefix:
                        - 185.189.196.0/22  # grenade
                        - 185.236.154.128/25  # grenade
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange: 3389
                  - name: allow-ssh
                    description: >-
                        allow: inbound tcp connections,
                        \ for: ssh,
                        \ from: allowlist,
                        \ to: any host,
                        \ on port: 22
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 111
                    sourceAddressPrefix:
                        - 185.189.196.0/22  # grenade
                        - 185.236.154.128/25  # grenade
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange: 22
                  - name: allow-winrm
                    description: >-
                        allow: inbound tcp connections,
                        \ for: winrm
                        \ over: http and https,
                        \ from: allowlist,
                        \ to: any host,
                        \ on ports: 5985, 5986
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 112
                    sourceAddressPrefix:
                        - 185.189.196.0/22  # grenade
                        - 185.236.154.128/25  # grenade
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange:
                        - 5985
                        - 5986
      tag: &tag
          - name: workerType
            value: gecko-t-win7-32-azure
          - name: sourceOrganisation
            value: mozilla-releng
          - name: sourceRepository
            value: OpenCloudConfig
          - name: sourceRevision
            value: 5017fdd
          - name: sourceScript
            value: userdata/rundsc.ps1
          - name: deploymentId
            value: 5017fdd
      bootstrap: &bootstrap
          executions: []
    - platform: azure
      group: rg-east-us-gecko-t
      region: East US
      hostname: *hostname
      machine: *machine
      agent: disable
      diagnostics: enable
      disk: *disk
      network:
          name: vn-east-us-gecko-t
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-gecko-t
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-gecko-t
              rules: *rules
      tag: *tag
      bootstrap: *bootstrap
    - platform: azure
      group: rg-east-us-2-gecko-t
      region: East US 2
      hostname: *hostname
      machine: *machine
      agent: disable
      diagnostics: enable
      disk: *disk
      network:
          name: vn-east-us-2-gecko-t
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-east-us-2-gecko-t
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-2-gecko-t
              rules: *rules
      tag: *tag
      bootstrap: *bootstrap
    - platform: azure
      group: rg-north-central-us-gecko-t
      region: North Central US
      hostname: *hostname
      machine: *machine
      agent: disable
      diagnostics: enable
      disk: *disk
      network:
          name: vn-north-central-us-gecko-t
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-north-central-us-gecko-t
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-north-central-us-gecko-t
              rules: *rules
      tag: *tag
      bootstrap: *bootstrap
    - platform: azure
      group: rg-south-central-us-gecko-t
      region: South Central US
      hostname: *hostname
      machine: *machine
      agent: disable
      diagnostics: enable
      disk: *disk
      network:
          name: vn-south-central-us-gecko-t
          prefix: '10.0.0.0/24'
          dns: *dns
          subnet:
              name: sn-south-central-us-gecko-t
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-south-central-us-gecko-t
              rules: *rules
      tag: *tag
      bootstrap: *bootstrap
log:
    - dsc-run
    - ed25519-public-key
    - fluentd
    - HaltOnIdle
    - MaintainSystem
    - nxlog
    - OpenCloudConfig
    - OpenSSH
    - Service_Control_Manager
    - stderr
    - stdout
    - sysprep-cbs
    - sysprep-ddaclsys
    - sysprep-setupact
    - sysprep-setupapi.app
    - sysprep-setupapi.dev
    - user32'
validation:
    instance:
        log:
            - program: 'sysprep-setupact'
              # yamllint disable-line rule:line-length
              match: '\[audit\.exe\] Successfully launched Sysprep with command line \[C:\\Windows\\system32\\sysprep\\sysprep\.exe  \/Generalize \/oobe \/shutdown\]'
            - program: 'OpenCloudConfig'
              # yamllint disable-line rule:line-length
              match: 'Invoke-Shutdown :: sysprep state: IMAGE_STATE_UNDEPLOYABLE, returning control to sysprep with exit code: 0'
