---
image:
    os: Windows 7
    edition: Professional
    language: en-US
    architecture: x86
    timezone: UTC
    hostname: 'cib-win7-32'
    gpu: true
    owner: Mozilla Infrastructure Operations
    organization: Mozilla Corporation
    partition: MBR
    format: VHD
    type: Fixed
    rdp: true
    obfuscate: true
    reseal:
        mode: Audit
        shutdown: true
    generalize:
        mode: OOBE
        shutdown: true
    reboot: 9
    network:
        location: Home
        dns:
            domain: win7-32-gpu.mozilla.com
            suffixes: null
            devolution: false
        interfaces:
            - alias: Local Area Connection
              dns:
                  domain: null
                  dynamic: false
                  register: false
                  search:
                      - '1.1.1.1'
                      - '1.0.0.1'
iso:
    source:
        platform: amazon
        bucket: windows-ami-builder
        key: iso/en_windows_7_professional_with_sp1_x86_dvd_u_677056.iso
    wimindex: 4
manager:
    pool:
        - domain: gecko-t
          variant: win7-32-gpu-azure
          capacity:
              minimum: 0
              maximum: 1
          timeout:
              registration: 3600
              reregistration: 86400
          locations:
              - eastus
          lifecycle: normal
          owner: grenade@mozilla.com
          provider: azure
          platform: azure
target:
    - platform: azure
      group: rg-east-us-gecko-t
      region: East US
      hostname:
          format: vm-{0}
          slug:
              type: uuid
              length: 12
      machine:
          cpu: 6
          ram: 56
          format: Standard_NV{0}_Promo
      disk:
          - os: true
            source: windows7-professional-en-us-x86-gpu
            variant: ssd
            size: 64
            caching: ReadWrite
            create: FromImage
          - os: false
            variant: ssd
            size: 128
          - os: false
            variant: ssd
            size: 128
      network:
          name: vn-east-us-gecko-t
          prefix: '10.0.0.0/24'
          dns:
              - '1.1.1.1'
              - '1.0.0.1'
          subnet:
              name: sn-east-us-gecko-t
              prefix: '10.0.0.0/24'
          flow:
              name: nsg-east-us-gecko-t
              rules:
                  - name: allow-rdp
                    # yamllint disable-line rule:line-length
                    description: 'allow: inbound tcp connections, for: rdp, from: allowlist, to: any host, on port: 3389'
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 110
                    sourceAddressPrefix:
                        - 185.189.196.0/22  # grenade
                        - 185.236.154.128/25  # grenade
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange: 3389
                  - name: allow-ssh
                    # yamllint disable-line rule:line-length
                    description: 'allow: inbound tcp connections, for: ssh, from: allowlist, to: any host, on port: 22'
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 111
                    sourceAddressPrefix:
                        - 185.189.196.0/22  # grenade
                        - 185.236.154.128/25  # grenade
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange: 22
                  - name: allow-winrm
                    # yamllint disable-line rule:line-length
                    description: 'allow: inbound tcp connections, for: winrm over http and https, from: allowlist, to: any host, on ports: 5985, 5986'
                    access: Allow
                    protocol: Tcp
                    direction: Inbound
                    priority: 112
                    sourceAddressPrefix:
                        - 185.189.196.0/22  # grenade
                        - 185.236.154.128/25  # grenade
                    sourcePortRange: '*'
                    destinationAddressPrefix: '*'
                    destinationPortRange:
                        - 5985
                        - 5986
      tag:
          - name: workerType
            value: gecko-t-win7-32-gpu-azure
          - name: sourceOrganisation
            value: mozilla-releng
          - name: sourceRepository
            value: OpenCloudConfig
          - name: sourceRevision
            value: 2c9c547
          - name: sourceScript
            value: userdata/rundsc.ps1
          - name: deploymentId
            value: 2c9c547
