---
- target:
      cloud:
          - amazon
          - azure
          - google
      os:
          - Windows 7
      architecture:
          - x86
      gpu:
          - true
          - false
  sources:
      - platform: amazon
        bucket: windows-ami-builder
        key: package/Win7-KB3191566-x86.msu
