---
description: build windows cloud images for taskcluster windows workloads
owner: grenade@mozilla.com
emailOnError: true
providerId: aws
config:
    minCapacity: 0
    maxCapacity: 24
    launchConfigs:
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1a
            SubnetId: subnet-0c938056fff37f311
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: c5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: &workerConfig
            shutdown:
                enabled: true
                afterIdleSeconds: 900
            billingCycleInterval: 21600
            capacityManagement:
                diskspaceThreshold: 30000000000
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1a
            SubnetId: subnet-0c938056fff37f311
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: m5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1a
            SubnetId: subnet-0c938056fff37f311
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: c5.xlarge
            BlockDeviceMappings:
              - DeviceName: "/dev/xvdb"
                Ebs:
                    DeleteOnTermination: true
                    VolumeSize: 120
                    VolumeType: gp2
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1b
            SubnetId: subnet-00d682e89c23d7a86
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: c5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1b
            SubnetId: subnet-00d682e89c23d7a86
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: m5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1b
            SubnetId: subnet-00d682e89c23d7a86
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: c5.xlarge
            BlockDeviceMappings:
              - DeviceName: "/dev/xvdb"
                Ebs:
                    DeleteOnTermination: true
                    VolumeSize: 120
                    VolumeType: gp2
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1c
            SubnetId: subnet-006eff582598db077
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: c5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1c
            SubnetId: subnet-006eff582598db077
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: m5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1c
            SubnetId: subnet-006eff582598db077
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: c5.xlarge
            BlockDeviceMappings:
              - DeviceName: "/dev/xvdb"
                Ebs:
                    DeleteOnTermination: true
                    VolumeSize: 120
                    VolumeType: gp2
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1d
            SubnetId: subnet-01454cff97aa89f34
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: c5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1d
            SubnetId: subnet-01454cff97aa89f34
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: m5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1d
            SubnetId: subnet-01454cff97aa89f34
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: c5.xlarge
            BlockDeviceMappings:
              - DeviceName: "/dev/xvdb"
                Ebs:
                    DeleteOnTermination: true
                    VolumeSize: 120
                    VolumeType: gp2
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1f
            SubnetId: subnet-0d8c0e26a6194119c
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: c5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1f
            SubnetId: subnet-0d8c0e26a6194119c
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: m5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-east-1
        launchConfig:
            ImageId: ami-076b0e106674bfcbf
            Placement:
                AvailabilityZone: us-east-1f
            SubnetId: subnet-0d8c0e26a6194119c
            SecurityGroupIds:
              - sg-01738525fc9991bd0
            InstanceType: c5.xlarge
            BlockDeviceMappings:
              - DeviceName: "/dev/xvdb"
                Ebs:
                    DeleteOnTermination: true
                    VolumeSize: 120
                    VolumeType: gp2
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-1
        launchConfig:
            ImageId: ami-052fe3192c0f750cb
            Placement:
                AvailabilityZone: us-west-1b
            SubnetId: subnet-01aac9d0ea7efdbc4
            SecurityGroupIds:
              - sg-0f52b4554cfc115e7
            InstanceType: c5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-1
        launchConfig:
            ImageId: ami-052fe3192c0f750cb
            Placement:
                AvailabilityZone: us-west-1b
            SubnetId: subnet-01aac9d0ea7efdbc4
            SecurityGroupIds:
              - sg-0f52b4554cfc115e7
            InstanceType: m5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-1
        launchConfig:
            ImageId: ami-052fe3192c0f750cb
            Placement:
                AvailabilityZone: us-west-1b
            SubnetId: subnet-01aac9d0ea7efdbc4
            SecurityGroupIds:
              - sg-0f52b4554cfc115e7
            InstanceType: c5.xlarge
            BlockDeviceMappings:
              - DeviceName: "/dev/xvdb"
                Ebs:
                    DeleteOnTermination: true
                    VolumeSize: 120
                    VolumeType: gp2
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-2
        launchConfig:
            ImageId: ami-0a89ebd64d44aebdb
            Placement:
                AvailabilityZone: us-west-2a
            SubnetId: subnet-06b091438ea962936
            SecurityGroupIds:
              - sg-07ca8c96f1574d42b
            InstanceType: c5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-2
        launchConfig:
            ImageId: ami-0a89ebd64d44aebdb
            Placement:
                AvailabilityZone: us-west-2a
            SubnetId: subnet-06b091438ea962936
            SecurityGroupIds:
              - sg-07ca8c96f1574d42b
            InstanceType: m5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-2
        launchConfig:
            ImageId: ami-0a89ebd64d44aebdb
            Placement:
                AvailabilityZone: us-west-2a
            SubnetId: subnet-06b091438ea962936
            SecurityGroupIds:
              - sg-07ca8c96f1574d42b
            InstanceType: c5.xlarge
            BlockDeviceMappings:
              - DeviceName: "/dev/xvdb"
                Ebs:
                    DeleteOnTermination: true
                    VolumeSize: 120
                    VolumeType: gp2
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-2
        launchConfig:
            ImageId: ami-0a89ebd64d44aebdb
            Placement:
                AvailabilityZone: us-west-2b
            SubnetId: subnet-00927443142f01ddf
            SecurityGroupIds:
              - sg-07ca8c96f1574d42b
            InstanceType: c5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-2
        launchConfig:
            ImageId: ami-0a89ebd64d44aebdb
            Placement:
                AvailabilityZone: us-west-2b
            SubnetId: subnet-00927443142f01ddf
            SecurityGroupIds:
              - sg-07ca8c96f1574d42b
            InstanceType: m5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-2
        launchConfig:
            ImageId: ami-0a89ebd64d44aebdb
            Placement:
                AvailabilityZone: us-west-2b
            SubnetId: subnet-00927443142f01ddf
            SecurityGroupIds:
              - sg-07ca8c96f1574d42b
            InstanceType: c5.xlarge
            BlockDeviceMappings:
              - DeviceName: "/dev/xvdb"
                Ebs:
                    DeleteOnTermination: true
                    VolumeSize: 120
                    VolumeType: gp2
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-2
        launchConfig:
            ImageId: ami-0a89ebd64d44aebdb
            Placement:
                AvailabilityZone: us-west-2c
            SubnetId: subnet-0ab2f88a3fa4ab7a0
            SecurityGroupIds:
              - sg-07ca8c96f1574d42b
            InstanceType: c5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-2
        launchConfig:
            ImageId: ami-0a89ebd64d44aebdb
            Placement:
                AvailabilityZone: us-west-2c
            SubnetId: subnet-0ab2f88a3fa4ab7a0
            SecurityGroupIds:
              - sg-07ca8c96f1574d42b
            InstanceType: m5d.xlarge
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
      - capacityPerInstance: 2
        region: us-west-2
        launchConfig:
            ImageId: ami-0a89ebd64d44aebdb
            Placement:
                AvailabilityZone: us-west-2c
            SubnetId: subnet-0ab2f88a3fa4ab7a0
            SecurityGroupIds:
              - sg-07ca8c96f1574d42b
            InstanceType: c5.xlarge
            BlockDeviceMappings:
              - DeviceName: "/dev/xvdb"
                Ebs:
                    DeleteOnTermination: true
                    VolumeSize: 120
                    VolumeType: gp2
            InstanceMarketOptions:
                MarketType: spot
        workerConfig: *workerConfig
