---
image:
    publisher: MicrosoftWindowsDesktop
    offer: Windows-10
    sku: 20h1-evd
azure:
    managed_image_resource_group_name: rg-packer-through-cib
    managed_image_storage_account_type: Standard_LRS
    build_location: eastus
    locations:
        - northcentralus
        #- southcentralus
        #- eastus
        #- northeurope
        #- westeurope
vm:
    size: Standard_NV6
    tags:
        base_image: win10642004azure
        worker_pool_id: gecko-t/win10-64-2004-base-gpu
        sourceOrganisation: markcor
        sourceRepository: ronin_puppet
        sourceBranch: cloud_windows
        deploymentId: d213ff4
        managed_by: packer
