---
image:
    publisher: MicrosoftWindowsDesktop
    offer: Windows-10
    sku: 20h1-evd
azure:
    managed_image_resource_group_name: rg-packer-through-cib
    managed_image_storage_account_type: Standard_LRS
    build_location: eastus
    locations:
        - centralus
        #- northcentralus
        #- southcentralus
        #- eastus
        #- eastus2
        #- westus
        #- westus2
vm:
    size: Standard_F8s_v2
    #disk_additional_size: 30
    tags:
        worker_pool_id: gecko-t/win10-64-2004-base
        workerType: gecko-t-win10-64-2004-test
        #sourceOrganisation: mozilla-platform-ops
        sourceOrganisation: markcor
        sourceRepository: ronin_puppet
        #sourceRevision: cloud_windows
        sourceBranch: cloud_windows
        deploymentId: fe2784e
        #deploymentId: bff70ed
        managed_by: packer
