---
image:
    publisher: MicrosoftWindowsDesktop
    offer: Windows-10
    sku: 20h1-evd
azure:
    managed_image_resource_group_name: rg-packer-through-cib
    managed_image_storage_account_type: Standard_LRS
    build_location: eastus
    locations:
        - northcentralus
        - southcentralus
        - eastus
        - northeurope
        - westeurope
vm:
    size: Standard_NV6
    disk_additional_size: 30
    tags:
        workerType: gecko-t-win10-64-2004-gpu
        sourceOrganisation: mozilla-platform-ops
        sourceRepository: ronin_puppet
        sourceRevision: cloud_windows
        deploymentId: 490f21f
        managed_by: packer
