---
image:
    publisher: MicrosoftWindowsDesktop
    offer: Windows-10
    sku: 20h1-evd
azure:
    managed_image_resource_group_name: rg-packer-through-cib
    managed_image_storage_account_type: Standard_LRS
    build_location: eastus
    locations:
        - northcentralus
        - southcentralus
        - eastus
        - northeurope
        - westeurope
vm:
    size: Standard_NV6
    #disk_additional_size: 30
    tags:
        base_image: win10642004azure
        worker_pool_id: gecko-t/win10-64-2004-base-gpu
        workerType: gecko-t-win10-64-2004-base-gpu
        #sourceOrganisation: mozilla-platform-ops
        sourceOrganisation: markcor
        sourceRepository: ronin_puppet
        #sourceRevision: cloud_windows
        sourceBranch: cloud_windows
        deploymentId: d213ff4
        #deploymentId: bff70ed
        managed_by: packer
