---
image:
    publisher: MicrosoftWindowsDesktop
    offer: Windows-10
    sku: win10-21h2-avd
azure:
    managed_image_resource_group_name: rg-packer-through-cib
    managed_image_storage_account_type: Standard_LRS
    build_location: eastus
    locations:
        - centralus
        - northcentralus
        - southcentralus
        - eastus
        - eastus2
        - westus
        - westus2
        - northeurope
        - westeurope
vm:
    size: Standard_F8s_v2
    tags:
        base_image: win10642009azure
        worker_pool_id: win10-64-2009
        sourceOrganisation: mozilla-platform-ops
        sourceRepository: ronin_puppet
        sourceBranch: cloud_windows
        deploymentId: c7b5588
        managed_by: packer