---
image:
    publisher: MicrosoftWindowsDesktop
    offer: Windows-10
    sku: 20h1-evd
azure:
    managed_image_resource_group_name: rg-packer-through-cib
    managed_image_storage_account_type: Standard_LRS
    build_location: eastus
    locations:
        - centralus
        - northcentralus
        - southcentralus
        - northeurope
vm:
    size: Standard_F8s_v2
    tags:
        base_image: win10642004azure
        worker_pool_id: gecko-t-win10-64-2004
        sourceOrganisation: markcor
        sourceRepository: ronin_puppet
        sourceBranch: cloud_windows
        deploymentId: bd3d676
        managed_by: packer
